In [1]:
import pandas as pd
In_State_Tuition_df = pd.read_excel('trends-college-pricing-excel-data.xlsx',header=1,sheet_name = "Table 6" ,skiprows = 53,usecols = "A:O",nrows =50)  
In_State_Tuition_df.rename(columns={"In Current Dollars": "University"},inplace = True)
In_State_Tuition_df

,University,STATE,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15,2015-16,2016-17,2017-18,2018-19,2019-20
0,University of Alaska Fairbanks,AK,4496,4828,5133,5316,5570,5898,5988,6182,6804,7184,7518,8087.0,8538
1,University of Alabama,AL,5700,6400,7000,7900,8600,9200,9450,9826,10170,10470,10780,10780.0,10780
2,University of Arkansas,AR,6038,6400,6459,6768,7174,7553,7818,8210,8522,8820,9062,9130.0,9384
3,University of Arizona,AZ,5037,5531,6855,8237,9299,10035,10391,10957,11403,11769,11877,12487.0,12711
4,University of California: Berkeley,CA,7164,7656,9749,10940,12835,12874,12864,12972,13431,13485,13928,14184.0,14253
5,University of Colorado at Boulder,CO,6635,7278,7932,8511,9152,9482,10529,10789,11091,11531,12086,12532.0,12500
6,University of Connecticut,CT,8842,9338,9886,10416,10670,11242,12022,12700,13364,14066,14880,15730.0,17226
7,University of Delaware,DE,8150,8646,9486,10208,11192,11682,12112,12342,12520,12830,13160,13680.0,14280
8,University of Florida,FL,3370,3790,4373,5045,5657,6143,6263,6313,6381,6381,6381,6381.0,6381
9,University of Georgia,GA,5259,5532,6172,7338,9472,9842,10262,10836,11622,11634,11818,11830.0,12080
10,University of Hawaii at Manoa,HI,5390,6259,7168,8096,9100,9404,9904,10620,11164,11732,11732,11970.0,12186
11,University of Iowa,IA,6293,6544,6824,7417,7765,8057,8061,8079,8104,8325,8964,9267.0,9606
12,University of Idaho,ID,4410,4632,4932,5402,5856,6212,6524,6784,7020,7232,7488,7864.0,8304
13,University of Illinois at Urbana-Champaign,IL,11130,12240,12528,13096,13838,14522,14750,15020,15626,15698,15868,16004.0,16210
14,Indiana University Bloomington,IN,7837,8231,8613,9028,9524,10033,10209,10388,10388,10388,10533,10681.0,10947
15,University of Kansas,KS,7146,7705,8206,8733,9222,9678,10107,10448,10802,11455,10824,11148.0,11166
16,University of Kentucky,KY,7096,7736,8123,8610,9128,9676,9966,10464,10936,11320,11772,12245.0,12360
17,Louisiana State University and Agricultural an...,LA,4543,5086,5233,5764,6354,7003,7880,8750,9842,10814,11374,11950.0,11962
18,University of Massachusetts Amherst,MA,9924,10417,11917,11917,12797,13230,13415,13443,14356,15156,15411,15887.0,16389
19,University of Maryland: College Park,MD,7969,8005,8053,8416,8655,8908,9161,9427,9996,10182,10399,10595.0,10779
20,University of Maine,ME,8330,9100,9626,10142,10588,10594,10600,10606,10610,10628,10902,11170.0,11438
21,University of Michigan,MI,10447,11037,11848,11837,12634,12994,13142,13486,13856,14402,14826,15262.0,15558
22,University of Minnesota: Twin Cities,MN,9885,10634,11287,12203,13022,13459,13618,13626,13790,14142,14417,14693.0,15027
23,University of Missouri: Columbia,MO,8099,8485,8501,8501,8989,9257,9415,9433,9509,9518,9787,9880.2,10269
24,University of Mississippi,MS,4932,5107,5106,5439,5792,6282,6760,7096,7444,7754,8300,8660.0,8828
25,University of Montana,MT,5141,5150,5330,5476,5722,5985,6045,6099,6158,6215,7063,7244.0,7354
26,University of North Carolina at Chapel Hill,NC,5340,5397,5625,6671,7008,7693,8340,8336,8591,8566,9005,8987.0,9046
27,University of North Dakota,ND,6130,6513,6726,6934,7092,7254,7508,7741,7965,8137,8447,8695.0,9736
28,University of Nebraska - Lincoln,NE,6216,6585,6857,7224,7563,7897,8075,8070,8279,8538,8901,9154.0,9366
29,University of New Hampshire,NH,11070,11756,12743,13672,15250,16422,16496,16552,16986,17624,18067,18499.0,18879
30,"Rutgers, The State University of New Jersey: N...",NJ,10686,11540,11886,12582,12754,13073,13499,13813,14131,14372,14638,14974.0,15407
31,University of New Mexico,NM,4571,4834,5101,5506,5809,6049,6447,6447,6664,6950,7146,7322.0,7556
32,University of Nevada: Reno,NV,4029,4561,4901,5561,6176,6603,6603,6639,6882,7143,7538,7764.0,8034
33,State University of New York at Buffalo,NY,6218,6285,7013,7136,7482,7989,8426,8871,9461,9574,9828,10099.0,10524
34,Ohio State University: Columbus Campus,OH,8676,8679,8726,9420,9735,10037,10037,10037,10037,10037,10591,10726.0,11084
35,University of Oklahoma,OK,6507,7423,7483,7864,8325,8706,8915,9495,10090,10881,11538,11763.0,11763
36,University of Oregon,OR,6168,6435,7428,8190,8789,9310,9763,9918,10289,10762,11571,11898.0,12720
37,Penn State University Park,PA,13639,13706,14416,15250,15984,16444,16992,17502,17514,17900,18436,18454.0,18450
38,University of Rhode Island,RI,8184,8678,9528,10476,11366,12450,12450,12506,12862,12884,13792,14138.0,14566
39,University of South Carolina,SC,8346,8838,9156,9786,10168,10488,10816,11158,11482,11854,12262,12616.0,12688
40,University of South Dakota,SD,5393,5828,6468,6762,7209,7704,8022,8022,8457,8457,8772,9061.0,9332
41,University of Tennessee: Knoxville,TN,5932,6250,6855,7382,8396,9092,11194,11876,12436,12724,12970,13006.0,13264
42,University of Texas at Austin,TX,7670,8532,8930,9416,9792,9790,9790,9798,9830,10110,10414,10622.0,10818
43,University of Utah,UT,4987,5285,5746,6274,6763,7139,7457,7935,8197,8518,8824,9222.0,9498
44,University of Virginia,VA,8500,9505,9672,10628,11576,12006,12458,12998,14468,15714,16076,16520.0,16640
45,University of Vermont,VT,12054,12844,13554,14066,14784,15284,15718,16196,16738,17300,17740,18276.0,18802
46,University of Washington,WA,6385,6907,7964,8973,10826,12383,12397,12394,11839,10753,10974,11207.0,11465
47,University of Wisconsin-Madison,WI,7188,7568,8310,8983,9671,10384,10403,10410,10415,10488,10533,10555.0,10725
48,West Virginia University,WV,4722,5100,5304,5406,5674,6090,6456,6960,7632,7992,8376,8856.0,8976
49,University of Wyoming,WY,3554,3621,3726,3927,4125,4278,4404,4646,4891,5055,5217,5400.0,5581

In [2]:
In_State_Tuition_df.to_excel("../processed/college_Tuition_in_State.xlsx",index=False)

In [3]:
Out_of_State_Tuition_df = pd.read_excel('trends-college-pricing-excel-data.xlsx',header=1,sheet_name = "Table 6" ,skiprows = 53,usecols = "A,R:AD",nrows =50)  
Out_of_State_Tuition_df.rename(columns={"In Current Dollars": "University",
                                       "2007-08.1":"2007-08",
                                       "2008-09.1":"2008-09",
                                       "2009-10.1":"2009-10",
                                       "2010-11.1":"2010-11",
                                       "2011-12.1":"2011-12",
                                       "2012-13.1":"2012-13",
                                       "2013-14.1":"2013-14",
                                       "2014-15.1":"2014-15",
                                       "2015-16.1":"2015-16",
                                       "2016-17.1":"2016-17",
                                       "2017-18.1":"2017-18",
                                       "2018-19.1":"2018-19",
                                       "2019-20.1":"2019-20"
                                       },inplace = True)
Out_of_State_Tuition_df

,University,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15,2015-16,2016-17,2017-18,2018-19,2019-20
0,University of Alaska Fairbanks,13466,14248,15036,15906,17210,18348,18948,19502,20784,21854,22908,24257,26208
1,University of Alabama,16518,18000,19200,20500,21900,22950,23950,24950,25950,26950,28100,29230,30250
2,University of Arkansas,14492,15278,15445,16000,17606,18434,19075,20302,21826,23168,24308,25168,25872
3,University of Arizona,16271,18665,22572,24597,25509,26231,27073,29421,32600,36017,35307,36386,36738
4,University of California: Berkeley,26784,28264,32418,33819,35713,35752,35742,35850,38139,40167,41942,43176,44007
5,University of Colorado at Boulder,24797,26756,28193,29493,30330,31378,32297,33151,34125,35079,36220,37286,38318
6,University of Connecticut,22786,24050,25584,26880,27566,29074,30970,32880,34908,35858,36948,38098,39894
7,University of Delaware,19400,21126,23408,25408,27462,28772,29932,30692,31420,32250,33150,34310,35710
8,University of Florida,17791,20640,23744,27322,27934,28420,28540,28590,28658,28658,28658,28658,28658
9,University of Georgia,20726,22343,25946,26946,27682,28052,28472,29046,29832,29844,30392,30404,31120
10,University of Hawaii at Manoa,14654,16915,19328,21536,23932,25652,27472,29412,31516,33764,33764,34002,34218
11,University of Iowa,19465,20658,22445,23713,25099,26279,26931,27409,27890,28413,30608,31233,31569
12,University of Idaho,14490,14712,15111,16994,18376,19000,19600,20314,21024,22040,23812,25500,27540
13,University of Illinois at Urbana-Champaign,25216,26024,26336,27238,27980,28664,29132,29646,30786,31320,31988,32574,33352
14,Indiana University Bloomington,22316,24769,26173,27689,29540,31483,32350,33241,33741,34246,34845,35456,36512
15,University of Kansas,17556,18909,20185,21538,22608,23748,24873,25731,26640,28239,26592,27358,28034
16,University of Kentucky,14896,15884,16723,17678,18740,19864,21052,22734,24268,26156,27856,29099,30680
17,Louisiana State University and Agricultural an...,12843,13800,14415,16549,19362,22279,25798,26467,27005,27491,28051,28627,28639
18,University of Massachusetts Amherst,20499,21914,23414,23813,25585,26645,26830,27812,30689,32389,33477,34570,35710
19,University of Maryland: College Park,22208,23076,24156,24831,26026,27287,28347,29720,31144,32045,33606,35216,36891
20,University of Maine,20540,22510,23972,25172,26308,27454,27970,28486,28880,29498,30282,30970,31748
21,University of Michigan,31301,33069,34937,36001,37782,39122,40392,41906,43476,45410,47476,49350,51200
22,University of Minnesota: Twin Cities,21515,14634,15529,16503,18022,18709,19868,20876,22210,23806,26603,30371,33325
23,University of Missouri: Columbia,18755,19558,19682,20516,21784,22440,22569,24460,25166,25892,26506,26949,28290
24,University of Mississippi,11436,12468,13046,13894,14797,16266,17728,19144,20674,22022,23564,24614,25100
25,University of Montana,15504,16425,17794,19172,20099,21077,21719,22372,23048,23669,24871,24959,26146
26,University of North Carolina at Chapel Hill,20988,22295,23609,25286,26834,28445,30122,33428,33673,33916,34588,35170,36225
27,University of North Dakota,14523,15325,15862,16373,16767,17170,17793,18409,18899,19291,20324,20759,13842
28,University of Nebraska - Lincoln,16236,17205,17926,18924,19848,20647,21403,22093,22446,23058,24201,24949,25806
29,University of New Hampshire,24030,25236,26992,27642,28570,28882,29216,29532,30256,31424,32637,33879,35409
30,"Rutgers, The State University of New Jersey: N...",19854,21488,22834,24044,25416,26393,27523,28591,29521,30023,30579,31282,32189
31,University of New Mexico,14942,15708,17234,18691,19999,20688,20688,20652,21304,21936,22037,22586,23292
32,University of Nevada: Reno,14839,15656,17698,18851,19771,20513,20513,20549,20792,21053,21726,22236,23085
33,State University of New York at Buffalo,12478,12545,15036,15546,16932,18609,20366,22291,24541,26814,27338,27769,28194
34,Ohio State University: Columbus Campus,21918,22298,22404,23604,24630,25445,25757,26537,27365,29229,29695,30742,32061
35,University of Oklahoma,15621,17404,17704,18295,19278,20343,21104,22269,23476,25203,26919,27144,27144
36,University of Oregon,19332,19992,23730,25830,27653,28660,29788,30888,32024,33442,34611,35478,36615
37,Penn State University Park,23712,24940,25972,27114,28066,28746,29566,30452,31346,32382,33664,34858,35514
38,University of Rhode Island,23038,24776,26198,27182,27454,28016,28016,28072,28852,28874,30042,30862,31686
39,University of South Carolina,21632,22908,23732,25362,26352,27644,28528,29440,30298,31282,32362,33298,33928
40,University of South Dakota,6631,7148,7892,8259,8924,9650,10104,10104,11337,11688,12020,12425,12807
41,University of Tennessee: Knoxville,17874,18908,20646,22420,25238,27282,29384,30066,30626,30914,31160,31196,31454
42,University of Texas at Austin,24544,27760,30006,31266,32379,33060,33824,34722,34836,35906,36984,37724,38228
43,University of Utah,15662,16601,18193,19841,21389,22642,23736,25267,26022,27039,28067,29215,30132
44,University of Virginia,27515,29798,31326,32902,35898,37336,39844,42184,43082,45058,45922,47562,49970
45,University of Vermont,27938,29682,31454,32630,34424,35612,36646,37844,39130,40364,41356,42516,43690
46,University of Washington,22131,23324,24639,25601,28310,31016,31971,33513,34143,34791,35538,36588,38166
47,University of Wisconsin-Madison,21438,21818,23095,24233,25421,26634,26653,26660,29665,32738,34783,36805,37785
48,West Virginia University,14600,15770,16402,17002,17844,18868,19632,20424,21432,22488,23616,24950,25320
49,University of Wyoming,10394,11031,11697,12237,12855,13428,14124,14876,15631,16215,16827,17490,18151

In [4]:
Out_of_State_Tuition_df.to_excel("../processed/college_Tuition_out_of_State.xlsx",index=False)