In [1]:
import pandas as pd

In [2]:
uniRank_path = 'State_PublicSchools_Rank.json'

In [3]:
uniRank_df=pd.read_json(uniRank_path)

In [4]:
uniRank_df

             State  overallRank  qualityRank  safetyRank
0    Massachusetts            1            2           1
1       New Jersey            2            1          11
2      Connecticut            3            3          12
3         Virginia            4            7           2
4          Vermont            5            6           4
5        Minnesota            6            7          23
6    New Hampshire            7            9           6
7         Nebraska            8           11           7
8     North Dakota            9            5          43
9          Wyoming           10            8          29
10       Wisconsin           11           10          27
11        Delaware           12           22           3
12        Kentucky           13           13          18
13            Iowa           14           12          33
14           Maine           15           20           5
15        Illinois           16           14          30
16        Colorado           17           17          10
17    Rhode Island           18           19           9
18        Maryland           19           15          17
19          Kansas           20           18          16
20    South Dakota           21           16          25
21         Indiana           22           21          28
22            Utah           23           24          13
23        New York           24           23          14
24         Montana           25           25          36
25         Florida           26           28          20
26    Pennsylvania           27           26          35
27            Ohio           28           30          19
28      Washington           29           31           8
29        Missouri           30           27          44
30  North Carolina           31           29          39
31           Idaho           32           35          22
32           Texas           33           33          31
33       Tennessee           34           36          26
34         Georgia           35           34          38
35          Hawaii           36           38          32
36        Michigan           37           32          49
37      California           38           40          37
38  South Carolina           39           39          41
39        Oklahoma           40           45          15
40        Arkansas           41           37          50
41          Alaska           42           46          21
42          Nevada           43           42          40
43          Oregon           44           41          46
44         Alabama           46           44          47
45   West Virginia           47           48          24
46         Arizona           48           50          34
47       Louisiana           49           49          51
48      New Mexico           50           51          45

In [5]:
states = {
        'AK': 'Alaska',
        'AL': 'Alabama',
        'AR': 'Arkansas',
        'AS': 'American Samoa',
        'AZ': 'Arizona',
        'CA': 'California',
        'CO': 'Colorado',
        'CT': 'Connecticut',
        'DC': 'District of Columbia',
        'DE': 'Delaware',
        'FL': 'Florida',
        'GA': 'Georgia',
        'GU': 'Guam',
        'HI': 'Hawaii',
        'IA': 'Iowa',
        'ID': 'Idaho',
        'IL': 'Illinois',
        'IN': 'Indiana',
        'KS': 'Kansas',
        'KY': 'Kentucky',
        'LA': 'Louisiana',
        'MA': 'Massachusetts',
        'MD': 'Maryland',
        'ME': 'Maine',
        'MI': 'Michigan',
        'MN': 'Minnesota',
        'MO': 'Missouri',
        'MP': 'Northern Mariana Islands',
        'MS': 'Mississippi',
        'MT': 'Montana',
        'NA': 'National',
        'NC': 'North Carolina',
        'ND': 'North Dakota',
        'NE': 'Nebraska',
        'NH': 'New Hampshire',
        'NJ': 'New Jersey',
        'NM': 'New Mexico',
        'NV': 'Nevada',
        'NY': 'New York',
        'OH': 'Ohio',
        'OK': 'Oklahoma',
        'OR': 'Oregon',
        'PA': 'Pennsylvania',
        'PR': 'Puerto Rico',
        'RI': 'Rhode Island',
        'SC': 'South Carolina',
        'SD': 'South Dakota',
        'TN': 'Tennessee',
        'TX': 'Texas',
        'UT': 'Utah',
        'VA': 'Virginia',
        'VI': 'Virgin Islands',
        'VT': 'Vermont',
        'WA': 'Washington',
        'WI': 'Wisconsin',
        'WV': 'West Virginia',
        'WY': 'Wyoming'
}

In [18]:
stateInitial = pd.DataFrame(list(states.items()),columns = ['State','Initials']) 
stateInitial

                       State Initials
0                     Alaska       AK
1                    Alabama       AL
2                   Arkansas       AR
3             American Samoa       AS
4                    Arizona       AZ
5                 California       CA
6                   Colorado       CO
7                Connecticut       CT
8       District of Columbia       DC
9                   Delaware       DE
10                   Florida       FL
11                   Georgia       GA
12                      Guam       GU
13                    Hawaii       HI
14                      Iowa       IA
15                     Idaho       ID
16                  Illinois       IL
17                   Indiana       IN
18                    Kansas       KS
19                  Kentucky       KY
20                 Louisiana       LA
21             Massachusetts       MA
22                  Maryland       MD
23                     Maine       ME
24                  Michigan       MI
25                 Minnesota       MN
26                  Missouri       MO
27  Northern Mariana Islands       MP
28               Mississippi       MS
29                   Montana       MT
30                  National       NA
31            North Carolina       NC
32              North Dakota       ND
33                  Nebraska       NE
34             New Hampshire       NH
35                New Jersey       NJ
36                New Mexico       NM
37                    Nevada       NV
38                  New York       NY
39                      Ohio       OH
40                  Oklahoma       OK
41                    Oregon       OR
42              Pennsylvania       PA
43               Puerto Rico       PR
44              Rhode Island       RI
45            South Carolina       SC
46              South Dakota       SD
47                 Tennessee       TN
48                     Texas       TX
49                      Utah       UT
50                  Virginia       VA
51            Virgin Islands       VI
52                   Vermont       VT
53                Washington       WA
54                 Wisconsin       WI
55             West Virginia       WV
56                   Wyoming       WY

In [19]:
uniStateRank = uniRank_df.merge(stateInitial,on='State',how='left')
uniStateRank

             State  overallRank  qualityRank  safetyRank Initials
0    Massachusetts            1            2           1       MA
1       New Jersey            2            1          11       NJ
2      Connecticut            3            3          12       CT
3         Virginia            4            7           2       VA
4          Vermont            5            6           4       VT
5        Minnesota            6            7          23       MN
6    New Hampshire            7            9           6       NH
7         Nebraska            8           11           7       NE
8     North Dakota            9            5          43       ND
9          Wyoming           10            8          29       WY
10       Wisconsin           11           10          27       WI
11        Delaware           12           22           3       DE
12        Kentucky           13           13          18       KY
13            Iowa           14           12          33       IA
14           Maine           15           20           5       ME
15        Illinois           16           14          30       IL
16        Colorado           17           17          10       CO
17    Rhode Island           18           19           9       RI
18        Maryland           19           15          17       MD
19          Kansas           20           18          16       KS
20    South Dakota           21           16          25       SD
21         Indiana           22           21          28       IN
22            Utah           23           24          13       UT
23        New York           24           23          14       NY
24         Montana           25           25          36       MT
25         Florida           26           28          20       FL
26    Pennsylvania           27           26          35       PA
27            Ohio           28           30          19       OH
28      Washington           29           31           8       WA
29        Missouri           30           27          44       MO
30  North Carolina           31           29          39       NC
31           Idaho           32           35          22       ID
32           Texas           33           33          31       TX
33       Tennessee           34           36          26       TN
34         Georgia           35           34          38       GA
35          Hawaii           36           38          32       HI
36        Michigan           37           32          49       MI
37      California           38           40          37       CA
38  South Carolina           39           39          41       SC
39        Oklahoma           40           45          15       OK
40        Arkansas           41           37          50       AR
41          Alaska           42           46          21       AK
42          Nevada           43           42          40       NV
43          Oregon           44           41          46       OR
44         Alabama           46           44          47       AL
45   West Virginia           47           48          24       WV
46         Arizona           48           50          34       AZ
47       Louisiana           49           49          51       LA
48      New Mexico           50           51          45       NM