In [1]:
import pandas as pd
import pprint as pp

In [2]:
# Read Algo input csv
Algo_input = pd.read_csv("Algo_data_input.csv")
Algo_input

    living_wage  income    debt  time_to_repay decision
0         33957   65383   57061       6.052419      Yes
1         24614   40961   50246      10.245713       No
2         29182   57060  129921      15.534472       No
3         34653  104308   53405       2.555691      Yes
4         30235   64336  100071       9.781825      Yes
5         24214   48841   56406       7.634710      Yes
6         32013   70617   54783       4.730339      Yes
7         32392  130567   73516       2.496087      Yes
8         25761   51612   48325       6.231223      Yes
9         29411   47528   13911       2.559475      Yes
10        26481   25284   87263    -243.004734       No
11        25270   82135   69783       4.090565      Yes
12        32625  136847   66710       2.133587      Yes
13        34412  112803   23080       0.981405      Yes
14        26567  120408   36852       1.309023      Yes
15        24488   35970  143810      41.749405       No
16        27603  108029   32739       1.356900      Yes
17        30942   71764   56071       4.578495      Yes
18        25950   74559   93300       6.397992      Yes
19        25373  114390   23053       0.863243      Yes
20        22141   54146  127895      13.320315       No
21        24256   29433   24605      15.842509       No
22        27144   98380  145046       6.787111      Yes
23        27570   47181   14234       2.419390      Yes
24        30428  110977   37194       1.539187      Yes
25        24022  117340   37891       1.353472      Yes
26        31744   57296   83481      10.890341       No
27        32657   29096   61380     -57.455771       No
28        30001   55676   89808      11.659591       No
29        24890  131794   74525       2.323736      Yes
30        28615   72990   35389       2.658329      Yes
31        27219  101217   37976       1.710677      Yes
32        22682   27839  112167      72.501454       No
33        24312   64971   78910       6.469252      Yes
34        34973   55596  129384      20.912573       No
35        35040   25532   90645     -31.778502       No
36        32855  104099  107551       5.032049      Yes
37        34910  107440  147771       6.791259      Yes
38        31172   39408   71072      28.764773       No
39        33027   68777  104822       9.773613      Yes
40        32230  101050   24419       1.182747      Yes
41        25910  124379  114004       3.859218      Yes
42        29302   60450   81241       8.694084      Yes
43        27708   69349  138052      11.050967       No
44        25445   66404   75323       6.129951      Yes
45        24634   36471   49958      14.068317       No
46        29836   55112  130712      17.237960       No
47        34871   89249  112578       6.900953      Yes
48        29444   34260   87637      60.656838       No
49        26033   31709  115474      67.814188       No

In [3]:
target = Algo_input["decision"]
target_names = ["Yes", "No"]

In [4]:
data = Algo_input.drop(["decision","time_to_repay"], axis=1)
feature_names = data.columns
data.head()

   living_wage  income    debt
0        33957   65383   57061
1        24614   40961   50246
2        29182   57060  129921
3        34653  104308   53405
4        30235   64336  100071

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=42)

# Support vector machine linear classifier
from sklearn.svm import SVC 
model_SVM = SVC(kernel='linear')
model_SVM.fit(X_train, y_train)

# Model Accuracy
# print('Test Acc: %.3f' % model.score(X_test, y_test))

# Calculate classification report
from sklearn.metrics import classification_report
predictions_SVM = model_SVM.predict(X_test)
print("SVM Model Classification Report")
print("------------------------------------------------------")
print(classification_report(y_test, predictions_SVM,
                            target_names=target_names))

SVM Model Classification Report
------------------------------------------------------
              precision    recall  f1-score   support

         Yes       1.00      0.75      0.86         4
          No       0.90      1.00      0.95         9

    accuracy                           0.92        13
   macro avg       0.95      0.88      0.90        13
weighted avg       0.93      0.92      0.92        13

In [13]:
from sklearn.model_selection import GridSearchCV
param_grid = {'C': [1, 5],
              'gamma': [0.0001, 0.001]}
grid = GridSearchCV(model_SVM, param_grid, verbose=3)
grid.fit(X_train, y_train)
predictions_grid = grid.predict(X_test)
print("SVM Model Classification Report with GridSearch")
print(classification_report(y_test, predictions_grid,
                            target_names=target_names))

Fitting 3 folds for each of 4 candidates, totalling 12 fits
[CV] C=1, gamma=0.0001 ...............................................
[CV] ................... C=1, gamma=0.0001, score=1.000, total=   0.0s
[CV] C=1, gamma=0.0001 ...............................................
[CV] ................... C=1, gamma=0.0001, score=1.000, total=   0.0s
[CV] C=1, gamma=0.0001 ...............................................
[CV] ................... C=1, gamma=0.0001, score=1.000, total=   0.0s
[CV] C=1, gamma=0.001 ................................................
[CV] .................... C=1, gamma=0.001, score=1.000, total=   0.0s
[CV] C=1, gamma=0.001 ................................................
[CV] .................... C=1, gamma=0.001, score=1.000, total=   0.0s
[CV] C=1, gamma=0.001 ................................................
[CV] .................... C=1, gamma=0.001, score=1.000, total=   0.0s
[CV] C=5, gamma=0.0001 ...............................................
[CV] ................... C=5, gamma=0.0001, score=1.000, total=   0.0s
[CV] C=5, gamma=0.0001 ...............................................
[CV] ................... C=5, gamma=0.0001, score=1.000, total=   0.0s
[CV] C=5, gamma=0.0001 ...............................................
[CV] ................... C=5, gamma=0.0001, score=1.000, total=   0.0s
[CV] C=5, gamma=0.001 ................................................
[CV] .................... C=5, gamma=0.001, score=1.000, total=   0.0s
[CV] C=5, gamma=0.001 ................................................
[CV] .................... C=5, gamma=0.001, score=1.000, total=   0.0s
[CV] C=5, gamma=0.001 ................................................
[CV] .................... C=5, gamma=0.001, score=1.000, total=   0.0s
SVM Model Classification Report with GridSearch
              precision    recall  f1-score   support

         Yes       1.00      0.75      0.86         4
          No       0.90      1.00      0.95         9

    accuracy                           0.92        13
   macro avg       0.95      0.88      0.90        13
weighted avg       0.93      0.92      0.92        13

C:\Users\Smiti\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  12 out of  12 | elapsed:    0.0s finished

In [18]:
from sklearn.linear_model import LogisticRegression
model_LR = LogisticRegression()
model_LR.fit(X_train, y_train)
predictions_LR = model_LR.predict(X_test)
print("Logistic Regression Model Classification Report")
print("------------------------------------------------------")
print(classification_report(y_test, predictions_LR,
                            target_names=target_names))

Logistic Regression Model Classification Report
------------------------------------------------------
              precision    recall  f1-score   support

         Yes       0.67      1.00      0.80         4
          No       1.00      0.78      0.88         9

    accuracy                           0.85        13
   macro avg       0.83      0.89      0.84        13
weighted avg       0.90      0.85      0.85        13

C:\Users\Smiti\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)