In [1]:
import pandas as pd

In [2]:
#Scarpe CPI data
url = 'https://inflationdata.com/Inflation/Consumer_Price_Index/HistoricalCPI.aspx?reloaded=true'
tables = pd.read_html(url)
CPI_df = tables[0]
CPI_df

,Year,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,Ave.
0,2020,257.971,258.678,258.115,256.389,256.394,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2019,251.712,252.776,254.202,255.548,256.092,256.143,256.571,256.558,256.759,257.346,257.208,256.974,255.657
2,2018,247.867,248.991,249.554,250.546,251.588,251.989,252.006,252.146,252.439,252.885,252.038,251.233,251.107
3,2017,242.839,243.603,243.801,244.524,244.733,244.955,244.786,245.519,246.819,246.663,246.669,246.524,245.120
4,2016,236.916,237.111,238.132,239.261,240.229,241.018,240.628,240.849,241.428,241.729,241.353,241.432,240.008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,1917,11.700,12.000,12.000,12.600,12.800,13.000,12.800,13.000,13.300,13.500,13.500,13.700,12.800
104,1916,10.400,10.400,10.500,10.600,10.700,10.800,10.800,10.900,11.100,11.300,11.500,11.600,10.900
105,1915,10.100,10.000,9.900,10.000,10.100,10.100,10.100,10.100,10.100,10.200,10.300,10.300,10.100
106,1914,10.000,9.900,9.900,9.800,9.900,9.900,10.000,10.200,10.200,10.100,10.200,10.100,10.000
107,1913,9.800,9.800,9.800,9.800,9.700,9.800,9.900,9.900,10.000,10.000,10.100,10.000,9.900

In [3]:
#filter only rows above year 2007
CPI_df = CPI_df.loc[(CPI_df["Year"] >= 2007)]

#Calculate Average for 2020
Average_2020 = (CPI_df.iloc[0]["Jan"] + CPI_df.iloc[0]["Feb"] + CPI_df.iloc[0]["Mar"] +CPI_df.iloc[0]["Apr"] 
                          +CPI_df.iloc[0]["May"])/5

for i, val in CPI_df.iterrows():
    if (i ==0):
        CPI_df["Avg_CPI"] = Average_2020

CPI_df["Ave."] = CPI_df["Ave."].fillna(CPI_df["Avg_CPI"])

CPI_df = CPI_df[["Year","Ave."]]
CPI_df.to_csv('../processed/Historical_CPI.csv', index=False)
CPI_df

C:\Users\Smiti\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\Smiti\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':

    Year      Ave.
0   2020  257.5094
1   2019  255.6570
2   2018  251.1070
3   2017  245.1200
4   2016  240.0080
5   2015  237.0170
6   2014  236.7360
7   2013  232.9570
8   2012  229.5940
9   2011  224.9390
10  2010  218.0560
11  2009  214.5370
12  2008  215.3030
13  2007  207.3420

In [4]:
#Read Student Enrollment data
Enrol_df =  pd.read_excel('Enrolled_Students.xlsx')  
Enrol_df

    Year    Total
0   2007  1985546
1   2008  2161485
2   2009  2058218
3   2010  2151856
4   2011  2100842
5   2012  2120753
6   2013  1961891
7   2014  1960782
8   2015  2052675
9   2016  2188376
10  2017  1914747
11  2018  2220228
12  2019  2077594
13  2020  2078283

In [5]:
#Scrape Student Loan Interest Rates data
IR_url='https://www.savingforcollege.com/article/historical-federal-student-interest-rates-and-fees'
tables1 = pd.read_html(IR_url)
IR_df=tables1[0]
IR_df.drop(IR_df.index[0],inplace=True)
IR_df

            0      1       2       3
1   2020-2021  Fixed  2.750%  2.750%
2   2019-2020  Fixed  4.529%  4.529%
3   2018-2019  Fixed  5.045%  5.045%
4   2017-2018  Fixed   4.45%   4.45%
5   2016-2017  Fixed   3.76%   3.76%
6   2015-2016  Fixed   4.29%   4.29%
7   2014-2015  Fixed   4.66%   4.66%
8   2013-2014  Fixed   3.86%   3.86%
9   2012-2013  Fixed   3.40%   6.80%
10  2011-2012  Fixed   3.40%   6.80%
11  2010-2011  Fixed   4.50%   6.80%
12  2009-2010  Fixed   5.60%   6.80%
13  2008-2009  Fixed   6.00%   6.80%
14  2007-2008  Fixed   6.80%   6.80%
15  2006-2007  Fixed   6.80%   6.80%

In [6]:
#clean up Interest rate DF
IR_df=IR_df[[0,2]]
IR_df.columns=['Year','IR']
IR_df[['FromYear','ToYear']] = IR_df.Year.str.split("-",expand=True)
IR_df['IR'] = IR_df['IR'].str.replace('%', '').astype(float)
IR_df_reduced=IR_df[['FromYear','IR']]
IR_df_reduced['FromYear']=IR_df_reduced['FromYear'].astype(int)
IR_df_reduced.to_excel("../processed/Student_loan_Interest_Rate.xlsx")
IR_df_reduced

C:\Users\Smiti\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py:3494: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]
C:\Users\Smiti\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

    FromYear     IR
1       2020  2.750
2       2019  4.529
3       2018  5.045
4       2017  4.450
5       2016  3.760
6       2015  4.290
7       2014  4.660
8       2013  3.860
9       2012  3.400
10      2011  3.400
11      2010  4.500
12      2009  5.600
13      2008  6.000
14      2007  6.800
15      2006  6.800

In [7]:
#Merge Data Frames based on inner joins
Combined_Enroll_CPI = pd.merge(Enrol_df,CPI_df,how="inner")
Combined_Enroll_CPI_IR = pd.merge(Combined_Enroll_CPI,IR_df_reduced,how="inner",left_on='Year', right_on='FromYear')
Combined_Enroll_CPI_IR

    Year    Total      Ave.  FromYear     IR
0   2007  1985546  207.3420      2007  6.800
1   2008  2161485  215.3030      2008  6.000
2   2009  2058218  214.5370      2009  5.600
3   2010  2151856  218.0560      2010  4.500
4   2011  2100842  224.9390      2011  3.400
5   2012  2120753  229.5940      2012  3.400
6   2013  1961891  232.9570      2013  3.860
7   2014  1960782  236.7360      2014  4.660
8   2015  2052675  237.0170      2015  4.290
9   2016  2188376  240.0080      2016  3.760
10  2017  1914747  245.1200      2017  4.450
11  2018  2220228  251.1070      2018  5.045
12  2019  2077594  255.6570      2019  4.529
13  2020  2078283  257.5094      2020  2.750

In [8]:
# X inputs to model from 2007 to 2018
Enroll_X_Inputs = Combined_Enroll_CPI_IR.loc[(Combined_Enroll_CPI_IR["Year"] <= 2018)]
X = Enroll_X_Inputs[["Ave.","Total","IR"]]
X

       Ave.    Total     IR
0   207.342  1985546  6.800
1   215.303  2161485  6.000
2   214.537  2058218  5.600
3   218.056  2151856  4.500
4   224.939  2100842  3.400
5   229.594  2120753  3.400
6   232.957  1961891  3.860
7   236.736  1960782  4.660
8   237.017  2052675  4.290
9   240.008  2188376  3.760
10  245.120  1914747  4.450
11  251.107  2220228  5.045

In [9]:
# New X inputs for 2019 and 2020 to be used in Model predictions for 2020 and 2021
X_new_inputs = Combined_Enroll_CPI_IR.tail(2)
X_new_inputs_reduced = X_new_inputs[["Ave.","Total","IR"]]
X_new_inputs_reduced

        Ave.    Total     IR
12  255.6570  2077594  4.529
13  257.5094  2078283  2.750

In [10]:
#Read In State College Tuition
Tuition_df =  pd.read_excel('../processed/college_Tuition_in_State.xlsx')  
Tuition_df

,University,STATE,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15,2015-16,2016-17,2017-18,2018-19,2019-20
0,University of Alaska Fairbanks,AK,4496,4828,5133,5316,5570,5898,5988,6182,6804,7184,7518,8087.0,8538
1,University of Alabama,AL,5700,6400,7000,7900,8600,9200,9450,9826,10170,10470,10780,10780.0,10780
2,University of Arkansas,AR,6038,6400,6459,6768,7174,7553,7818,8210,8522,8820,9062,9130.0,9384
3,University of Arizona,AZ,5037,5531,6855,8237,9299,10035,10391,10957,11403,11769,11877,12487.0,12711
4,University of California: Berkeley,CA,7164,7656,9749,10940,12835,12874,12864,12972,13431,13485,13928,14184.0,14253
5,University of Colorado at Boulder,CO,6635,7278,7932,8511,9152,9482,10529,10789,11091,11531,12086,12532.0,12500
6,University of Connecticut,CT,8842,9338,9886,10416,10670,11242,12022,12700,13364,14066,14880,15730.0,17226
7,University of Delaware,DE,8150,8646,9486,10208,11192,11682,12112,12342,12520,12830,13160,13680.0,14280
8,University of Florida,FL,3370,3790,4373,5045,5657,6143,6263,6313,6381,6381,6381,6381.0,6381
9,University of Georgia,GA,5259,5532,6172,7338,9472,9842,10262,10836,11622,11634,11818,11830.0,12080
10,University of Hawaii at Manoa,HI,5390,6259,7168,8096,9100,9404,9904,10620,11164,11732,11732,11970.0,12186
11,University of Iowa,IA,6293,6544,6824,7417,7765,8057,8061,8079,8104,8325,8964,9267.0,9606
12,University of Idaho,ID,4410,4632,4932,5402,5856,6212,6524,6784,7020,7232,7488,7864.0,8304
13,University of Illinois at Urbana-Champaign,IL,11130,12240,12528,13096,13838,14522,14750,15020,15626,15698,15868,16004.0,16210
14,Indiana University Bloomington,IN,7837,8231,8613,9028,9524,10033,10209,10388,10388,10388,10533,10681.0,10947
15,University of Kansas,KS,7146,7705,8206,8733,9222,9678,10107,10448,10802,11455,10824,11148.0,11166
16,University of Kentucky,KY,7096,7736,8123,8610,9128,9676,9966,10464,10936,11320,11772,12245.0,12360
17,Louisiana State University and Agricultural an...,LA,4543,5086,5233,5764,6354,7003,7880,8750,9842,10814,11374,11950.0,11962
18,University of Massachusetts Amherst,MA,9924,10417,11917,11917,12797,13230,13415,13443,14356,15156,15411,15887.0,16389
19,University of Maryland: College Park,MD,7969,8005,8053,8416,8655,8908,9161,9427,9996,10182,10399,10595.0,10779
20,University of Maine,ME,8330,9100,9626,10142,10588,10594,10600,10606,10610,10628,10902,11170.0,11438
21,University of Michigan,MI,10447,11037,11848,11837,12634,12994,13142,13486,13856,14402,14826,15262.0,15558
22,University of Minnesota: Twin Cities,MN,9885,10634,11287,12203,13022,13459,13618,13626,13790,14142,14417,14693.0,15027
23,University of Missouri: Columbia,MO,8099,8485,8501,8501,8989,9257,9415,9433,9509,9518,9787,9880.2,10269
24,University of Mississippi,MS,4932,5107,5106,5439,5792,6282,6760,7096,7444,7754,8300,8660.0,8828
25,University of Montana,MT,5141,5150,5330,5476,5722,5985,6045,6099,6158,6215,7063,7244.0,7354
26,University of North Carolina at Chapel Hill,NC,5340,5397,5625,6671,7008,7693,8340,8336,8591,8566,9005,8987.0,9046
27,University of North Dakota,ND,6130,6513,6726,6934,7092,7254,7508,7741,7965,8137,8447,8695.0,9736
28,University of Nebraska - Lincoln,NE,6216,6585,6857,7224,7563,7897,8075,8070,8279,8538,8901,9154.0,9366
29,University of New Hampshire,NH,11070,11756,12743,13672,15250,16422,16496,16552,16986,17624,18067,18499.0,18879
30,"Rutgers, The State University of New Jersey: N...",NJ,10686,11540,11886,12582,12754,13073,13499,13813,14131,14372,14638,14974.0,15407
31,University of New Mexico,NM,4571,4834,5101,5506,5809,6049,6447,6447,6664,6950,7146,7322.0,7556
32,University of Nevada: Reno,NV,4029,4561,4901,5561,6176,6603,6603,6639,6882,7143,7538,7764.0,8034
33,State University of New York at Buffalo,NY,6218,6285,7013,7136,7482,7989,8426,8871,9461,9574,9828,10099.0,10524
34,Ohio State University: Columbus Campus,OH,8676,8679,8726,9420,9735,10037,10037,10037,10037,10037,10591,10726.0,11084
35,University of Oklahoma,OK,6507,7423,7483,7864,8325,8706,8915,9495,10090,10881,11538,11763.0,11763
36,University of Oregon,OR,6168,6435,7428,8190,8789,9310,9763,9918,10289,10762,11571,11898.0,12720
37,Penn State University Park,PA,13639,13706,14416,15250,15984,16444,16992,17502,17514,17900,18436,18454.0,18450
38,University of Rhode Island,RI,8184,8678,9528,10476,11366,12450,12450,12506,12862,12884,13792,14138.0,14566
39,University of South Carolina,SC,8346,8838,9156,9786,10168,10488,10816,11158,11482,11854,12262,12616.0,12688
40,University of South Dakota,SD,5393,5828,6468,6762,7209,7704,8022,8022,8457,8457,8772,9061.0,9332
41,University of Tennessee: Knoxville,TN,5932,6250,6855,7382,8396,9092,11194,11876,12436,12724,12970,13006.0,13264
42,University of Texas at Austin,TX,7670,8532,8930,9416,9792,9790,9790,9798,9830,10110,10414,10622.0,10818
43,University of Utah,UT,4987,5285,5746,6274,6763,7139,7457,7935,8197,8518,8824,9222.0,9498
44,University of Virginia,VA,8500,9505,9672,10628,11576,12006,12458,12998,14468,15714,16076,16520.0,16640
45,University of Vermont,VT,12054,12844,13554,14066,14784,15284,15718,16196,16738,17300,17740,18276.0,18802
46,University of Washington,WA,6385,6907,7964,8973,10826,12383,12397,12394,11839,10753,10974,11207.0,11465
47,University of Wisconsin-Madison,WI,7188,7568,8310,8983,9671,10384,10403,10410,10415,10488,10533,10555.0,10725
48,West Virginia University,WV,4722,5100,5304,5406,5674,6090,6456,6960,7632,7992,8376,8856.0,8976
49,University of Wyoming,WY,3554,3621,3726,3927,4125,4278,4404,4646,4891,5055,5217,5400.0,5581

In [11]:
#Prediction for In-State Tuition Fees
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
university = {}

# loop through all universities
for i in Tuition_df.index:
    Univ = Tuition_df['University'][i]
    print(Tuition_df['University'][i])
    University = Tuition_df.iloc[[i]]
    University_T = University.transpose()
    University_T = University_T[i]
    y_values = University_T.values

    #prepare y values one year ahead of X year(i.e from 2008-2019)
    y = []
    for i in y_values:
        try:
            i_int = int(i)
            y.append(i_int)
        except:
            pass
    y.pop(0)
    
    #Model, Fit, Predict
    X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)
    model = LinearRegression()
    model.fit(X_train, y_train)
    training_score = model.score(X_train, y_train)
    testing_score = model.score(X_test, y_test)
    print(f"Model Training Score: {training_score}")
    print(f"Model Testing Score: {testing_score}")
    
    prediction_2020 = model.predict([X_new_inputs_reduced.iloc[0]])
    prediction_2021 = model.predict([X_new_inputs_reduced.iloc[1]])
    
    print(f"Actual In-State Tuition 2019-2020: {y[11]}")
    print(f"Pedicated In-State Tuition 2020-2021: {prediction_2020}")
    print(f"Pedicated In-State Tuition 2021-2022: {prediction_2021}")
    print("----------------------------------------")
    university[Univ] = {"2020-21": prediction_2020[0],
                       "2021-22":prediction_2021[0]}

University of Alaska Fairbanks
Model Training Score: 0.9665699598831178
Model Testing Score: 0.9219863605498423
Actual In-State Tuition 2019-2020: 8538
Pedicated In-State Tuition 2020-2021: [8657.48906857]
Pedicated In-State Tuition 2021-2022: [8551.948784]
----------------------------------------
University of Alabama
Model Training Score: 0.949933564014297
Model Testing Score: 0.9653621641668017
Actual In-State Tuition 2019-2020: 10780
Pedicated In-State Tuition 2020-2021: [11643.39345538]
Pedicated In-State Tuition 2021-2022: [12413.55782711]
----------------------------------------
University of Arkansas
Model Training Score: 0.9727084851225128
Model Testing Score: 0.9495512162766556
Actual In-State Tuition 2019-2020: 9384
Pedicated In-State Tuition 2020-2021: [9935.87670632]
Pedicated In-State Tuition 2021-2022: [10193.38517721]
----------------------------------------
University of Arizona
Model Training Score: 0.9461218049985181
Model Testing Score: 0.9680269720622094
Actual In-State Tuition 2019-2020: 12711
Pedicated In-State Tuition 2020-2021: [13753.34850129]
Pedicated In-State Tuition 2021-2022: [14804.49682391]
----------------------------------------
University of California: Berkeley
Model Training Score: 0.8428949814573143
Model Testing Score: 0.8923593410246026
Actual In-State Tuition 2019-2020: 14253
Pedicated In-State Tuition 2020-2021: [14813.08551762]
Pedicated In-State Tuition 2021-2022: [16086.55082449]
----------------------------------------
University of Colorado at Boulder
Model Training Score: 0.969792018463564
Model Testing Score: 0.9752485409647851
Actual In-State Tuition 2019-2020: 12500
Pedicated In-State Tuition 2020-2021: [13322.96723881]
Pedicated In-State Tuition 2021-2022: [13844.73929699]
----------------------------------------
University of Connecticut
Model Training Score: 0.9807160547642441
Model Testing Score: 0.9655362765933952
Actual In-State Tuition 2019-2020: 17226
Pedicated In-State Tuition 2020-2021: [17514.87904802]
Pedicated In-State Tuition 2021-2022: [17295.92688093]
----------------------------------------
University of Delaware
Model Training Score: 0.9643608421053074
Model Testing Score: 0.9943740280931345
Actual In-State Tuition 2019-2020: 14280
Pedicated In-State Tuition 2020-2021: [14729.16750622]
Pedicated In-State Tuition 2021-2022: [15500.50562386]
----------------------------------------
University of Florida
Model Training Score: 0.9505471820698068
Model Testing Score: 0.9239023253655354
Actual In-State Tuition 2019-2020: 6381
Pedicated In-State Tuition 2020-2021: [6927.34283517]
Pedicated In-State Tuition 2021-2022: [7747.50866504]
----------------------------------------
University of Georgia
Model Training Score: 0.9194089445500303
Model Testing Score: 0.9701961160154017
Actual In-State Tuition 2019-2020: 12080
Pedicated In-State Tuition 2020-2021: [13530.46014304]
Pedicated In-State Tuition 2021-2022: [15004.30931491]
----------------------------------------
University of Hawaii at Manoa
Model Training Score: 0.9361918085619702
Model Testing Score: 0.9558839971008743
Actual In-State Tuition 2019-2020: 12186
Pedicated In-State Tuition 2020-2021: [13322.69499884]
Pedicated In-State Tuition 2021-2022: [13969.40607415]
----------------------------------------
University of Iowa
Model Training Score: 0.8996091031523707
Model Testing Score: 0.88513006445651
Actual In-State Tuition 2019-2020: 9606
Pedicated In-State Tuition 2020-2021: [9469.5003212]
Pedicated In-State Tuition 2021-2022: [9790.44815041]
----------------------------------------
University of Idaho
Model Training Score: 0.9720408498094908
Model Testing Score: 0.9944906162515874
Actual In-State Tuition 2019-2020: 8304
Pedicated In-State Tuition 2020-2021: [8639.23198398]
Pedicated In-State Tuition 2021-2022: [8965.4352004]
----------------------------------------
University of Illinois at Urbana-Champaign
Model Training Score: 0.9654073339963276
Model Testing Score: 0.9795306495703303
Actual In-State Tuition 2019-2020: 16210
Pedicated In-State Tuition 2020-2021: [17042.45528364]
Pedicated In-State Tuition 2021-2022: [17712.94914566]
----------------------------------------
Indiana University Bloomington
Model Training Score: 0.9809317548959474
Model Testing Score: 0.9823429759621208
Actual In-State Tuition 2019-2020: 10947
Pedicated In-State Tuition 2020-2021: [11335.18785324]
Pedicated In-State Tuition 2021-2022: [11927.97574674]
----------------------------------------
University of Kansas
Model Training Score: 0.9235231957007395
Model Testing Score: 0.9398249557520678
Actual In-State Tuition 2019-2020: 11166
Pedicated In-State Tuition 2020-2021: [12143.3490351]
Pedicated In-State Tuition 2021-2022: [12658.06390449]
----------------------------------------
University of Kentucky
Model Training Score: 0.9727219961627784
Model Testing Score: 0.9708026104437951
Actual In-State Tuition 2019-2020: 12360
Pedicated In-State Tuition 2020-2021: [12993.3827873]
Pedicated In-State Tuition 2021-2022: [13307.30773372]
----------------------------------------
Louisiana State University and Agricultural and Mechanical College
Model Training Score: 0.9607090033716049
Model Testing Score: 0.9197598124513454
Actual In-State Tuition 2019-2020: 11962
Pedicated In-State Tuition 2020-2021: [13323.78456619]
Pedicated In-State Tuition 2021-2022: [13440.47857809]
----------------------------------------
University of Massachusetts Amherst
Model Training Score: 0.9480594273394927
Model Testing Score: 0.9572123542773979
Actual In-State Tuition 2019-2020: 16389
Pedicated In-State Tuition 2020-2021: [16774.06408254]
Pedicated In-State Tuition 2021-2022: [16962.52988482]
----------------------------------------
University of Maryland: College Park
Model Training Score: 0.9586835041690055
Model Testing Score: 0.9548381098261031
Actual In-State Tuition 2019-2020: 10779
Pedicated In-State Tuition 2020-2021: [11247.61881001]
Pedicated In-State Tuition 2021-2022: [11314.40675098]
----------------------------------------
University of Maine
Model Training Score: 0.8079742954726308
Model Testing Score: 0.8975290688631625
Actual In-State Tuition 2019-2020: 11438
Pedicated In-State Tuition 2020-2021: [11344.53746131]
Pedicated In-State Tuition 2021-2022: [11664.51335443]
----------------------------------------
University of Michigan
Model Training Score: 0.9696672291885278
Model Testing Score: 0.960505289290473
Actual In-State Tuition 2019-2020: 15558
Pedicated In-State Tuition 2020-2021: [15888.59104482]
Pedicated In-State Tuition 2021-2022: [16126.50938473]
----------------------------------------
University of Minnesota: Twin Cities
Model Training Score: 0.9239473694313881
Model Testing Score: 0.9904932655888072
Actual In-State Tuition 2019-2020: 15027
Pedicated In-State Tuition 2020-2021: [15355.53720932]
Pedicated In-State Tuition 2021-2022: [16161.54215335]
----------------------------------------
University of Missouri: Columbia
Model Training Score: 0.9867422725254157
Model Testing Score: 0.7697524776544518
Actual In-State Tuition 2019-2020: 10269
Pedicated In-State Tuition 2020-2021: [10372.12691025]
Pedicated In-State Tuition 2021-2022: [10685.23851551]
----------------------------------------
University of Mississippi
Model Training Score: 0.9858514610901835
Model Testing Score: 0.9183008946540916
Actual In-State Tuition 2019-2020: 8828
Pedicated In-State Tuition 2020-2021: [9343.23239511]
Pedicated In-State Tuition 2021-2022: [9584.45580218]
----------------------------------------
University of Montana
Model Training Score: 0.9573228104267978
Model Testing Score: 0.7197333371309618
Actual In-State Tuition 2019-2020: 7354
Pedicated In-State Tuition 2020-2021: [7242.66067037]
Pedicated In-State Tuition 2021-2022: [7372.80599713]
----------------------------------------
University of North Carolina at Chapel Hill
Model Training Score: 0.9568189581247694
Model Testing Score: 0.9757596164394587
Actual In-State Tuition 2019-2020: 9046
Pedicated In-State Tuition 2020-2021: [9808.43279621]
Pedicated In-State Tuition 2021-2022: [10637.19108468]
----------------------------------------
University of North Dakota
Model Training Score: 0.9724131922374166
Model Testing Score: 0.9588504544940002
Actual In-State Tuition 2019-2020: 9736
Pedicated In-State Tuition 2020-2021: [9662.97526646]
Pedicated In-State Tuition 2021-2022: [9555.34952682]
----------------------------------------
University of Nebraska - Lincoln
Model Training Score: 0.9632965839235565
Model Testing Score: 0.9531239091216633
Actual In-State Tuition 2019-2020: 9366
Pedicated In-State Tuition 2020-2021: [9511.95081616]
Pedicated In-State Tuition 2021-2022: [9806.11619378]
----------------------------------------
University of New Hampshire
Model Training Score: 0.9581022321724157
Model Testing Score: 0.9929530103844849
Actual In-State Tuition 2019-2020: 18879
Pedicated In-State Tuition 2020-2021: [19648.69431131]
Pedicated In-State Tuition 2021-2022: [21089.34928952]
----------------------------------------
Rutgers, The State University of New Jersey: New Brunswick/Piscataway Campus
Model Training Score: 0.9601491596134338
Model Testing Score: 0.9919269519302583
Actual In-State Tuition 2019-2020: 15407
Pedicated In-State Tuition 2020-2021: [15810.8148122]
Pedicated In-State Tuition 2021-2022: [15997.19426729]
----------------------------------------
University of New Mexico

Model Training Score: 0.9613715954470015
Model Testing Score: 0.9921022083792403
Actual In-State Tuition 2019-2020: 7556
Pedicated In-State Tuition 2020-2021: [7852.62193441]
Pedicated In-State Tuition 2021-2022: [8144.11932627]
----------------------------------------
University of Nevada: Reno
Model Training Score: 0.9272305970309941
Model Testing Score: 0.9791376682559769
Actual In-State Tuition 2019-2020: 8034
Pedicated In-State Tuition 2020-2021: [8237.10038332]
Pedicated In-State Tuition 2021-2022: [8789.01981006]
----------------------------------------
State University of New York at Buffalo
Model Training Score: 0.9898630545024234
Model Testing Score: 0.9719683212910822
Actual In-State Tuition 2019-2020: 10524
Pedicated In-State Tuition 2020-2021: [11185.20579832]
Pedicated In-State Tuition 2021-2022: [11300.02750699]
----------------------------------------
Ohio State University: Columbus Campus
Model Training Score: 0.8563332881986565
Model Testing Score: 0.9321658086372985
Actual In-State Tuition 2019-2020: 11084
Pedicated In-State Tuition 2020-2021: [11019.63407117]
Pedicated In-State Tuition 2021-2022: [11435.63293805]
----------------------------------------
University of Oklahoma
Model Training Score: 0.9450156439226695
Model Testing Score: 0.8638684685652245
Actual In-State Tuition 2019-2020: 11763
Pedicated In-State Tuition 2020-2021: [12380.32408185]
Pedicated In-State Tuition 2021-2022: [12438.14001707]
----------------------------------------
University of Oregon
Model Training Score: 0.9633595328419936
Model Testing Score: 0.9805504835414668
Actual In-State Tuition 2019-2020: 12720
Pedicated In-State Tuition 2020-2021: [12956.27850939]
Pedicated In-State Tuition 2021-2022: [13381.9854763]
----------------------------------------
Penn State University Park
Model Training Score: 0.9623631097068037
Model Testing Score: 0.9665238071797086
Actual In-State Tuition 2019-2020: 18450
Pedicated In-State Tuition 2020-2021: [19289.92208694]
Pedicated In-State Tuition 2021-2022: [20054.62452231]
----------------------------------------
University of Rhode Island
Model Training Score: 0.9528404732199077
Model Testing Score: 0.9884828101422425
Actual In-State Tuition 2019-2020: 14566
Pedicated In-State Tuition 2020-2021: [14943.06527988]
Pedicated In-State Tuition 2021-2022: [15963.07996265]
----------------------------------------
University of South Carolina
Model Training Score: 0.9557624042920586
Model Testing Score: 0.9673145981810837
Actual In-State Tuition 2019-2020: 12688
Pedicated In-State Tuition 2020-2021: [13163.61179038]
Pedicated In-State Tuition 2021-2022: [13447.44918743]
----------------------------------------
University of South Dakota
Model Training Score: 0.9829132351771773
Model Testing Score: 0.9954432213158498
Actual In-State Tuition 2019-2020: 9332
Pedicated In-State Tuition 2020-2021: [9710.43231209]
Pedicated In-State Tuition 2021-2022: [10102.32432271]
----------------------------------------
University of Tennessee: Knoxville
Model Training Score: 0.9666636514042428
Model Testing Score: 0.91535169364579
Actual In-State Tuition 2019-2020: 13264
Pedicated In-State Tuition 2020-2021: [15347.77826316]
Pedicated In-State Tuition 2021-2022: [16306.21291994]
----------------------------------------
University of Texas at Austin
Model Training Score: 0.8397575290715915
Model Testing Score: 0.9032234765327576
Actual In-State Tuition 2019-2020: 10818
Pedicated In-State Tuition 2020-2021: [10733.91089782]
Pedicated In-State Tuition 2021-2022: [10965.46527506]
----------------------------------------
University of Utah
Model Training Score: 0.9692175582018042
Model Testing Score: 0.9902798063952568
Actual In-State Tuition 2019-2020: 9498
Pedicated In-State Tuition 2020-2021: [10010.93121594]
Pedicated In-State Tuition 2021-2022: [10327.00201146]
----------------------------------------
University of Virginia
Model Training Score: 0.9138696061713005
Model Testing Score: 0.9366412822593463
Actual In-State Tuition 2019-2020: 16640
Pedicated In-State Tuition 2020-2021: [17834.23341297]
Pedicated In-State Tuition 2021-2022: [18094.7521552]
----------------------------------------
University of Vermont
Model Training Score: 0.9711488127043906
Model Testing Score: 0.986428469097028
Actual In-State Tuition 2019-2020: 18802
Pedicated In-State Tuition 2020-2021: [19396.77439974]
Pedicated In-State Tuition 2021-2022: [19725.11737377]
----------------------------------------
University of Washington
Model Training Score: 0.9211270670985987
Model Testing Score: 0.7436849262480216
Actual In-State Tuition 2019-2020: 11465
Pedicated In-State Tuition 2020-2021: [12315.20113345]
Pedicated In-State Tuition 2021-2022: [14786.33545242]
----------------------------------------
University of Wisconsin-Madison
Model Training Score: 0.9616806334599736
Model Testing Score: 0.9497085638261753
Actual In-State Tuition 2019-2020: 10725
Pedicated In-State Tuition 2020-2021: [11208.91743124]
Pedicated In-State Tuition 2021-2022: [12161.60456725]
----------------------------------------
West Virginia University
Model Training Score: 0.9779876410799585
Model Testing Score: 0.9292032186313671
Actual In-State Tuition 2019-2020: 8976
Pedicated In-State Tuition 2020-2021: [9578.60230937]
Pedicated In-State Tuition 2021-2022: [9504.18304331]
----------------------------------------
University of Wyoming
Model Training Score: 0.9672091858361753
Model Testing Score: 0.9731174859374173
Actual In-State Tuition 2019-2020: 5581
Pedicated In-State Tuition 2020-2021: [5814.09579401]
Pedicated In-State Tuition 2021-2022: [5858.40761156]
----------------------------------------

In [12]:
# In State Tuition Prediction to Data Frame
Predicted_df = pd.DataFrame.from_dict(university)
Predicted_df = Predicted_df.transpose()
Predicted_df

                                                         2020-21       2021-22
University of Alaska Fairbanks                       8657.489069   8551.948784
University of Alabama                               11643.393455  12413.557827
University of Arkansas                               9935.876706  10193.385177
University of Arizona                               13753.348501  14804.496824
University of California: Berkeley                  14813.085518  16086.550824
University of Colorado at Boulder                   13322.967239  13844.739297
University of Connecticut                           17514.879048  17295.926881
University of Delaware                              14729.167506  15500.505624
University of Florida                                6927.342835   7747.508665
University of Georgia                               13530.460143  15004.309315
University of Hawaii at Manoa                       13322.694999  13969.406074
University of Iowa                                   9469.500321   9790.448150
University of Idaho                                  8639.231984   8965.435200
University of Illinois at Urbana-Champaign          17042.455284  17712.949146
Indiana University Bloomington                      11335.187853  11927.975747
University of Kansas                                12143.349035  12658.063904
University of Kentucky                              12993.382787  13307.307734
Louisiana State University and Agricultural and...  13323.784566  13440.478578
University of Massachusetts Amherst                 16774.064083  16962.529885
University of Maryland: College Park                11247.618810  11314.406751
University of Maine                                 11344.537461  11664.513354
University of Michigan                              15888.591045  16126.509385
University of Minnesota: Twin Cities                15355.537209  16161.542153
University of Missouri: Columbia                    10372.126910  10685.238516
University of Mississippi                            9343.232395   9584.455802
University of Montana                                7242.660670   7372.805997
University of North Carolina at Chapel Hill          9808.432796  10637.191085
University of North Dakota                           9662.975266   9555.349527
University of Nebraska - Lincoln                     9511.950816   9806.116194
University of New Hampshire                         19648.694311  21089.349290
Rutgers, The State University of New Jersey: Ne...  15810.814812  15997.194267
University of New Mexico                             7852.621934   8144.119326
University of Nevada: Reno                           8237.100383   8789.019810
State University of New York at Buffalo             11185.205798  11300.027507
Ohio State University: Columbus Campus              11019.634071  11435.632938
University of Oklahoma                              12380.324082  12438.140017
University of Oregon                                12956.278509  13381.985476
Penn State University Park                          19289.922087  20054.624522
University of Rhode Island                          14943.065280  15963.079963
University of South Carolina                        13163.611790  13447.449187
University of South Dakota                           9710.432312  10102.324323
University of Tennessee: Knoxville                  15347.778263  16306.212920
University of Texas at Austin                       10733.910898  10965.465275
University of Utah                                  10010.931216  10327.002011
University of Virginia                              17834.233413  18094.752155
University of Vermont                               19396.774400  19725.117374
University of Washington                            12315.201133  14786.335452
University of Wisconsin-Madison                     11208.917431  12161.604567
West Virginia University                             9578.602309   9504.183043
University of Wyoming                                5814.095794   5858.407612

In [13]:
# Prediction merged with intial data frame
In_State_Tuition_df = pd.merge(Tuition_df,Predicted_df,how = "inner",left_on="University", right_on=Predicted_df.index)
In_State_Tuition_df

,University,STATE,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15,2015-16,2016-17,2017-18,2018-19,2019-20,2020-21,2021-22
0,University of Alaska Fairbanks,AK,4496,4828,5133,5316,5570,5898,5988,6182,6804,7184,7518,8087.0,8538,8657.489069,8551.948784
1,University of Alabama,AL,5700,6400,7000,7900,8600,9200,9450,9826,10170,10470,10780,10780.0,10780,11643.393455,12413.557827
2,University of Arkansas,AR,6038,6400,6459,6768,7174,7553,7818,8210,8522,8820,9062,9130.0,9384,9935.876706,10193.385177
3,University of Arizona,AZ,5037,5531,6855,8237,9299,10035,10391,10957,11403,11769,11877,12487.0,12711,13753.348501,14804.496824
4,University of California: Berkeley,CA,7164,7656,9749,10940,12835,12874,12864,12972,13431,13485,13928,14184.0,14253,14813.085518,16086.550824
5,University of Colorado at Boulder,CO,6635,7278,7932,8511,9152,9482,10529,10789,11091,11531,12086,12532.0,12500,13322.967239,13844.739297
6,University of Connecticut,CT,8842,9338,9886,10416,10670,11242,12022,12700,13364,14066,14880,15730.0,17226,17514.879048,17295.926881
7,University of Delaware,DE,8150,8646,9486,10208,11192,11682,12112,12342,12520,12830,13160,13680.0,14280,14729.167506,15500.505624
8,University of Florida,FL,3370,3790,4373,5045,5657,6143,6263,6313,6381,6381,6381,6381.0,6381,6927.342835,7747.508665
9,University of Georgia,GA,5259,5532,6172,7338,9472,9842,10262,10836,11622,11634,11818,11830.0,12080,13530.460143,15004.309315
10,University of Hawaii at Manoa,HI,5390,6259,7168,8096,9100,9404,9904,10620,11164,11732,11732,11970.0,12186,13322.694999,13969.406074
11,University of Iowa,IA,6293,6544,6824,7417,7765,8057,8061,8079,8104,8325,8964,9267.0,9606,9469.500321,9790.448150
12,University of Idaho,ID,4410,4632,4932,5402,5856,6212,6524,6784,7020,7232,7488,7864.0,8304,8639.231984,8965.435200
13,University of Illinois at Urbana-Champaign,IL,11130,12240,12528,13096,13838,14522,14750,15020,15626,15698,15868,16004.0,16210,17042.455284,17712.949146
14,Indiana University Bloomington,IN,7837,8231,8613,9028,9524,10033,10209,10388,10388,10388,10533,10681.0,10947,11335.187853,11927.975747
15,University of Kansas,KS,7146,7705,8206,8733,9222,9678,10107,10448,10802,11455,10824,11148.0,11166,12143.349035,12658.063904
16,University of Kentucky,KY,7096,7736,8123,8610,9128,9676,9966,10464,10936,11320,11772,12245.0,12360,12993.382787,13307.307734
17,Louisiana State University and Agricultural an...,LA,4543,5086,5233,5764,6354,7003,7880,8750,9842,10814,11374,11950.0,11962,13323.784566,13440.478578
18,University of Massachusetts Amherst,MA,9924,10417,11917,11917,12797,13230,13415,13443,14356,15156,15411,15887.0,16389,16774.064083,16962.529885
19,University of Maryland: College Park,MD,7969,8005,8053,8416,8655,8908,9161,9427,9996,10182,10399,10595.0,10779,11247.618810,11314.406751
20,University of Maine,ME,8330,9100,9626,10142,10588,10594,10600,10606,10610,10628,10902,11170.0,11438,11344.537461,11664.513354
21,University of Michigan,MI,10447,11037,11848,11837,12634,12994,13142,13486,13856,14402,14826,15262.0,15558,15888.591045,16126.509385
22,University of Minnesota: Twin Cities,MN,9885,10634,11287,12203,13022,13459,13618,13626,13790,14142,14417,14693.0,15027,15355.537209,16161.542153
23,University of Missouri: Columbia,MO,8099,8485,8501,8501,8989,9257,9415,9433,9509,9518,9787,9880.2,10269,10372.126910,10685.238516
24,University of Mississippi,MS,4932,5107,5106,5439,5792,6282,6760,7096,7444,7754,8300,8660.0,8828,9343.232395,9584.455802
25,University of Montana,MT,5141,5150,5330,5476,5722,5985,6045,6099,6158,6215,7063,7244.0,7354,7242.660670,7372.805997
26,University of North Carolina at Chapel Hill,NC,5340,5397,5625,6671,7008,7693,8340,8336,8591,8566,9005,8987.0,9046,9808.432796,10637.191085
27,University of North Dakota,ND,6130,6513,6726,6934,7092,7254,7508,7741,7965,8137,8447,8695.0,9736,9662.975266,9555.349527
28,University of Nebraska - Lincoln,NE,6216,6585,6857,7224,7563,7897,8075,8070,8279,8538,8901,9154.0,9366,9511.950816,9806.116194
29,University of New Hampshire,NH,11070,11756,12743,13672,15250,16422,16496,16552,16986,17624,18067,18499.0,18879,19648.694311,21089.349290
30,"Rutgers, The State University of New Jersey: N...",NJ,10686,11540,11886,12582,12754,13073,13499,13813,14131,14372,14638,14974.0,15407,15810.814812,15997.194267
31,University of New Mexico,NM,4571,4834,5101,5506,5809,6049,6447,6447,6664,6950,7146,7322.0,7556,7852.621934,8144.119326
32,University of Nevada: Reno,NV,4029,4561,4901,5561,6176,6603,6603,6639,6882,7143,7538,7764.0,8034,8237.100383,8789.019810
33,State University of New York at Buffalo,NY,6218,6285,7013,7136,7482,7989,8426,8871,9461,9574,9828,10099.0,10524,11185.205798,11300.027507
34,Ohio State University: Columbus Campus,OH,8676,8679,8726,9420,9735,10037,10037,10037,10037,10037,10591,10726.0,11084,11019.634071,11435.632938
35,University of Oklahoma,OK,6507,7423,7483,7864,8325,8706,8915,9495,10090,10881,11538,11763.0,11763,12380.324082,12438.140017
36,University of Oregon,OR,6168,6435,7428,8190,8789,9310,9763,9918,10289,10762,11571,11898.0,12720,12956.278509,13381.985476
37,Penn State University Park,PA,13639,13706,14416,15250,15984,16444,16992,17502,17514,17900,18436,18454.0,18450,19289.922087,20054.624522
38,University of Rhode Island,RI,8184,8678,9528,10476,11366,12450,12450,12506,12862,12884,13792,14138.0,14566,14943.065280,15963.079963
39,University of South Carolina,SC,8346,8838,9156,9786,10168,10488,10816,11158,11482,11854,12262,12616.0,12688,13163.611790,13447.449187
40,University of South Dakota,SD,5393,5828,6468,6762,7209,7704,8022,8022,8457,8457,8772,9061.0,9332,9710.432312,10102.324323
41,University of Tennessee: Knoxville,TN,5932,6250,6855,7382,8396,9092,11194,11876,12436,12724,12970,13006.0,13264,15347.778263,16306.212920
42,University of Texas at Austin,TX,7670,8532,8930,9416,9792,9790,9790,9798,9830,10110,10414,10622.0,10818,10733.910898,10965.465275
43,University of Utah,UT,4987,5285,5746,6274,6763,7139,7457,7935,8197,8518,8824,9222.0,9498,10010.931216,10327.002011
44,University of Virginia,VA,8500,9505,9672,10628,11576,12006,12458,12998,14468,15714,16076,16520.0,16640,17834.233413,18094.752155
45,University of Vermont,VT,12054,12844,13554,14066,14784,15284,15718,16196,16738,17300,17740,18276.0,18802,19396.774400,19725.117374
46,University of Washington,WA,6385,6907,7964,8973,10826,12383,12397,12394,11839,10753,10974,11207.0,11465,12315.201133,14786.335452
47,University of Wisconsin-Madison,WI,7188,7568,8310,8983,9671,10384,10403,10410,10415,10488,10533,10555.0,10725,11208.917431,12161.604567
48,West Virginia University,WV,4722,5100,5304,5406,5674,6090,6456,6960,7632,7992,8376,8856.0,8976,9578.602309,9504.183043
49,University of Wyoming,WY,3554,3621,3726,3927,4125,4278,4404,4646,4891,5055,5217,5400.0,5581,5814.095794,5858.407612

In [14]:
# read out of state Tuition data
Out_State_Tuition_df = pd.read_excel('../processed/college_Tuition_out_of_State.xlsx')  
Out_State_Tuition_df

,University,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15,2015-16,2016-17,2017-18,2018-19,2019-20
0,University of Alaska Fairbanks,13466,14248,15036,15906,17210,18348,18948,19502,20784,21854,22908,24257,26208
1,University of Alabama,16518,18000,19200,20500,21900,22950,23950,24950,25950,26950,28100,29230,30250
2,University of Arkansas,14492,15278,15445,16000,17606,18434,19075,20302,21826,23168,24308,25168,25872
3,University of Arizona,16271,18665,22572,24597,25509,26231,27073,29421,32600,36017,35307,36386,36738
4,University of California: Berkeley,26784,28264,32418,33819,35713,35752,35742,35850,38139,40167,41942,43176,44007
5,University of Colorado at Boulder,24797,26756,28193,29493,30330,31378,32297,33151,34125,35079,36220,37286,38318
6,University of Connecticut,22786,24050,25584,26880,27566,29074,30970,32880,34908,35858,36948,38098,39894
7,University of Delaware,19400,21126,23408,25408,27462,28772,29932,30692,31420,32250,33150,34310,35710
8,University of Florida,17791,20640,23744,27322,27934,28420,28540,28590,28658,28658,28658,28658,28658
9,University of Georgia,20726,22343,25946,26946,27682,28052,28472,29046,29832,29844,30392,30404,31120
10,University of Hawaii at Manoa,14654,16915,19328,21536,23932,25652,27472,29412,31516,33764,33764,34002,34218
11,University of Iowa,19465,20658,22445,23713,25099,26279,26931,27409,27890,28413,30608,31233,31569
12,University of Idaho,14490,14712,15111,16994,18376,19000,19600,20314,21024,22040,23812,25500,27540
13,University of Illinois at Urbana-Champaign,25216,26024,26336,27238,27980,28664,29132,29646,30786,31320,31988,32574,33352
14,Indiana University Bloomington,22316,24769,26173,27689,29540,31483,32350,33241,33741,34246,34845,35456,36512
15,University of Kansas,17556,18909,20185,21538,22608,23748,24873,25731,26640,28239,26592,27358,28034
16,University of Kentucky,14896,15884,16723,17678,18740,19864,21052,22734,24268,26156,27856,29099,30680
17,Louisiana State University and Agricultural an...,12843,13800,14415,16549,19362,22279,25798,26467,27005,27491,28051,28627,28639
18,University of Massachusetts Amherst,20499,21914,23414,23813,25585,26645,26830,27812,30689,32389,33477,34570,35710
19,University of Maryland: College Park,22208,23076,24156,24831,26026,27287,28347,29720,31144,32045,33606,35216,36891
20,University of Maine,20540,22510,23972,25172,26308,27454,27970,28486,28880,29498,30282,30970,31748
21,University of Michigan,31301,33069,34937,36001,37782,39122,40392,41906,43476,45410,47476,49350,51200
22,University of Minnesota: Twin Cities,21515,14634,15529,16503,18022,18709,19868,20876,22210,23806,26603,30371,33325
23,University of Missouri: Columbia,18755,19558,19682,20516,21784,22440,22569,24460,25166,25892,26506,26949,28290
24,University of Mississippi,11436,12468,13046,13894,14797,16266,17728,19144,20674,22022,23564,24614,25100
25,University of Montana,15504,16425,17794,19172,20099,21077,21719,22372,23048,23669,24871,24959,26146
26,University of North Carolina at Chapel Hill,20988,22295,23609,25286,26834,28445,30122,33428,33673,33916,34588,35170,36225
27,University of North Dakota,14523,15325,15862,16373,16767,17170,17793,18409,18899,19291,20324,20759,13842
28,University of Nebraska - Lincoln,16236,17205,17926,18924,19848,20647,21403,22093,22446,23058,24201,24949,25806
29,University of New Hampshire,24030,25236,26992,27642,28570,28882,29216,29532,30256,31424,32637,33879,35409
30,"Rutgers, The State University of New Jersey: N...",19854,21488,22834,24044,25416,26393,27523,28591,29521,30023,30579,31282,32189
31,University of New Mexico,14942,15708,17234,18691,19999,20688,20688,20652,21304,21936,22037,22586,23292
32,University of Nevada: Reno,14839,15656,17698,18851,19771,20513,20513,20549,20792,21053,21726,22236,23085
33,State University of New York at Buffalo,12478,12545,15036,15546,16932,18609,20366,22291,24541,26814,27338,27769,28194
34,Ohio State University: Columbus Campus,21918,22298,22404,23604,24630,25445,25757,26537,27365,29229,29695,30742,32061
35,University of Oklahoma,15621,17404,17704,18295,19278,20343,21104,22269,23476,25203,26919,27144,27144
36,University of Oregon,19332,19992,23730,25830,27653,28660,29788,30888,32024,33442,34611,35478,36615
37,Penn State University Park,23712,24940,25972,27114,28066,28746,29566,30452,31346,32382,33664,34858,35514
38,University of Rhode Island,23038,24776,26198,27182,27454,28016,28016,28072,28852,28874,30042,30862,31686
39,University of South Carolina,21632,22908,23732,25362,26352,27644,28528,29440,30298,31282,32362,33298,33928
40,University of South Dakota,6631,7148,7892,8259,8924,9650,10104,10104,11337,11688,12020,12425,12807
41,University of Tennessee: Knoxville,17874,18908,20646,22420,25238,27282,29384,30066,30626,30914,31160,31196,31454
42,University of Texas at Austin,24544,27760,30006,31266,32379,33060,33824,34722,34836,35906,36984,37724,38228
43,University of Utah,15662,16601,18193,19841,21389,22642,23736,25267,26022,27039,28067,29215,30132
44,University of Virginia,27515,29798,31326,32902,35898,37336,39844,42184,43082,45058,45922,47562,49970
45,University of Vermont,27938,29682,31454,32630,34424,35612,36646,37844,39130,40364,41356,42516,43690
46,University of Washington,22131,23324,24639,25601,28310,31016,31971,33513,34143,34791,35538,36588,38166
47,University of Wisconsin-Madison,21438,21818,23095,24233,25421,26634,26653,26660,29665,32738,34783,36805,37785
48,West Virginia University,14600,15770,16402,17002,17844,18868,19632,20424,21432,22488,23616,24950,25320
49,University of Wyoming,10394,11031,11697,12237,12855,13428,14124,14876,15631,16215,16827,17490,18151

In [15]:
#Prediction for Out-of-State Tuition Fees
out_university = {}
for i in Out_State_Tuition_df.index:
    Univ = Tuition_df['University'][i]
    print(Out_State_Tuition_df['University'][i])
    University = Out_State_Tuition_df.iloc[[i]]
    University_T = University.transpose()
    University_T = University_T[i]
    y_values = University_T.values

    #prepare y values one year ahead of X year(i.e from 2008-2019)
    y = []
    for i in y_values:
        try:
            i_int = int(i)
            y.append(i_int)
        except:
            pass
    y.pop(0)
    
    #Model, Fit, Predict
    X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)
    model = LinearRegression()
    model.fit(X_train, y_train)
    training_score = model.score(X_train, y_train)
    testing_score = model.score(X_test, y_test)
    print(f"Model Training Score: {training_score}")
    print(f"Model Testing Score: {testing_score}")
    
    prediction_2020 = model.predict([X_new_inputs_reduced.iloc[0]])
    prediction_2021 = model.predict([X_new_inputs_reduced.iloc[1]])
    
    print(f"Actual Out-of-State Tuition 2019-2020: {y[11]}")
    print(f"Pedicated Out-of-State Tuition 2020-2021: {prediction_2020}")
    print(f"Pedicated Out-of-State Tuition 2021-2022: {prediction_2021}")
    print("----------------------------------------")
    out_university[Univ] = {"2020-21": prediction_2020[0],
                       "2021-22":prediction_2021[0]}

University of Alaska Fairbanks
Model Training Score: 0.9734251803699486
Model Testing Score: 0.9501211857630857
Actual Out-of-State Tuition 2019-2020: 26208
Pedicated Out-of-State Tuition 2020-2021: [26671.33713986]
Pedicated Out-of-State Tuition 2021-2022: [27070.76237094]
----------------------------------------
University of Alabama
Model Training Score: 0.9720369469633952
Model Testing Score: 0.9832293251164834
Actual Out-of-State Tuition 2019-2020: 30250
Pedicated Out-of-State Tuition 2020-2021: [31453.69709617]
Pedicated Out-of-State Tuition 2021-2022: [32210.80234324]
----------------------------------------
University of Arkansas
Model Training Score: 0.9624791222590522
Model Testing Score: 0.9191658957044542
Actual Out-of-State Tuition 2019-2020: 25872
Pedicated Out-of-State Tuition 2020-2021: [27239.08308938]
Pedicated Out-of-State Tuition 2021-2022: [27540.48245422]
----------------------------------------
University of Arizona
Model Training Score: 0.8915348516895412
Model Testing Score: 0.8771628125855886
Actual Out-of-State Tuition 2019-2020: 36738
Pedicated Out-of-State Tuition 2020-2021: [39903.14838764]
Pedicated Out-of-State Tuition 2021-2022: [39444.4898743]
----------------------------------------
University of California: Berkeley
Model Training Score: 0.8989271104591166
Model Testing Score: 0.8639565605152018
Actual Out-of-State Tuition 2019-2020: 44007
Pedicated Out-of-State Tuition 2020-2021: [44120.24105017]
Pedicated Out-of-State Tuition 2021-2022: [44148.10032444]
----------------------------------------
University of Colorado at Boulder
Model Training Score: 0.9716956621278081
Model Testing Score: 0.9791669116332432
Actual Out-of-State Tuition 2019-2020: 38318
Pedicated Out-of-State Tuition 2020-2021: [39276.35300767]
Pedicated Out-of-State Tuition 2021-2022: [39735.56085531]
----------------------------------------
University of Connecticut
Model Training Score: 0.9833620852581104
Model Testing Score: 0.9722301572070706
Actual Out-of-State Tuition 2019-2020: 39894
Pedicated Out-of-State Tuition 2020-2021: [42177.30859327]
Pedicated Out-of-State Tuition 2021-2022: [42200.42633234]
----------------------------------------
University of Delaware
Model Training Score: 0.9654275723211021
Model Testing Score: 0.9954552876391276
Actual Out-of-State Tuition 2019-2020: 35710
Pedicated Out-of-State Tuition 2020-2021: [37082.8831662]
Pedicated Out-of-State Tuition 2021-2022: [38763.37715209]
----------------------------------------
University of Florida
Model Training Score: 0.7189026190086287
Model Testing Score: 0.5953208852321827
Actual Out-of-State Tuition 2019-2020: 28658
Pedicated Out-of-State Tuition 2020-2021: [29528.79139736]
Pedicated Out-of-State Tuition 2021-2022: [31297.20094329]
----------------------------------------
University of Georgia
Model Training Score: 0.9510171545799874
Model Testing Score: 0.7236864625070987
Actual Out-of-State Tuition 2019-2020: 31120
Pedicated Out-of-State Tuition 2020-2021: [31934.44496953]
Pedicated Out-of-State Tuition 2021-2022: [32376.10143187]
----------------------------------------
University of Hawaii at Manoa
Model Training Score: 0.9423754292048232
Model Testing Score: 0.9441171066055085
Actual Out-of-State Tuition 2019-2020: 34218
Pedicated Out-of-State Tuition 2020-2021: [38265.44480674]
Pedicated Out-of-State Tuition 2021-2022: [40045.60570947]
----------------------------------------
University of Iowa
Model Training Score: 0.970981298908595
Model Testing Score: 0.9497863257465343
Actual Out-of-State Tuition 2019-2020: 31569
Pedicated Out-of-State Tuition 2020-2021: [32249.82710844]
Pedicated Out-of-State Tuition 2021-2022: [33383.93514924]
----------------------------------------
University of Idaho
Model Training Score: 0.940636038886966
Model Testing Score: 0.9088980828753246
Actual Out-of-State Tuition 2019-2020: 27540
Pedicated Out-of-State Tuition 2020-2021: [27427.5299147]
Pedicated Out-of-State Tuition 2021-2022: [27929.34796157]
----------------------------------------
University of Illinois at Urbana-Champaign
Model Training Score: 0.9623203851786573
Model Testing Score: 0.9732468365353946
Actual Out-of-State Tuition 2019-2020: 33352
Pedicated Out-of-State Tuition 2020-2021: [34136.89282771]
Pedicated Out-of-State Tuition 2021-2022: [34430.78299956]
----------------------------------------
Indiana University Bloomington
Model Training Score: 0.983298229040336
Model Testing Score: 0.9937881533553923
Actual Out-of-State Tuition 2019-2020: 36512
Pedicated Out-of-State Tuition 2020-2021: [38297.33908927]
Pedicated Out-of-State Tuition 2021-2022: [40239.2148537]
----------------------------------------
University of Kansas
Model Training Score: 0.9335960543318182
Model Testing Score: 0.9240322695850266
Actual Out-of-State Tuition 2019-2020: 28034
Pedicated Out-of-State Tuition 2020-2021: [30311.76277867]
Pedicated Out-of-State Tuition 2021-2022: [31442.92461353]
----------------------------------------
University of Kentucky
Model Training Score: 0.9726453249261585
Model Testing Score: 0.9388033839176108
Actual Out-of-State Tuition 2019-2020: 30680
Pedicated Out-of-State Tuition 2020-2021: [31998.35079813]
Pedicated Out-of-State Tuition 2021-2022: [31861.77369]
----------------------------------------
Louisiana State University and Agricultural and Mechanical College
Model Training Score: 0.982337261651403
Model Testing Score: 0.9510702940106801
Actual Out-of-State Tuition 2019-2020: 28639
Pedicated Out-of-State Tuition 2020-2021: [32828.39976362]
Pedicated Out-of-State Tuition 2021-2022: [36605.84895526]
----------------------------------------
University of Massachusetts Amherst
Model Training Score: 0.9437440697224264
Model Testing Score: 0.9476005518852378
Actual Out-of-State Tuition 2019-2020: 35710
Pedicated Out-of-State Tuition 2020-2021: [37064.39245081]
Pedicated Out-of-State Tuition 2021-2022: [36958.86377666]
----------------------------------------
University of Maryland: College Park
Model Training Score: 0.9856282138377145
Model Testing Score: 0.964184923409033
Actual Out-of-State Tuition 2019-2020: 36891
Pedicated Out-of-State Tuition 2020-2021: [37924.32444032]
Pedicated Out-of-State Tuition 2021-2022: [38028.27166587]
----------------------------------------
University of Maine
Model Training Score: 0.9707701880611802
Model Testing Score: 0.993817775840792
Actual Out-of-State Tuition 2019-2020: 31748
Pedicated Out-of-State Tuition 2020-2021: [32562.77643439]
Pedicated Out-of-State Tuition 2021-2022: [33626.30115819]
----------------------------------------
University of Michigan
Model Training Score: 0.9756752442256743
Model Testing Score: 0.9549122613317333
Actual Out-of-State Tuition 2019-2020: 51200
Pedicated Out-of-State Tuition 2020-2021: [52343.22080636]
Pedicated Out-of-State Tuition 2021-2022: [52635.7299859]
----------------------------------------
University of Minnesota: Twin Cities
Model Training Score: 0.9687576323999355
Model Testing Score: 0.790747952706055
Actual Out-of-State Tuition 2019-2020: 33325
Pedicated Out-of-State Tuition 2020-2021: [32477.65602625]
Pedicated Out-of-State Tuition 2021-2022: [31927.89971479]
----------------------------------------
University of Missouri: Columbia
Model Training Score: 0.958901903199633
Model Testing Score: 0.9637184266278547
Actual Out-of-State Tuition 2019-2020: 28290
Pedicated Out-of-State Tuition 2020-2021: [29455.62821469]
Pedicated Out-of-State Tuition 2021-2022: [29723.21023581]
----------------------------------------
University of Mississippi
Model Training Score: 0.979553845081754
Model Testing Score: 0.9324245505588049
Actual Out-of-State Tuition 2019-2020: 25100
Pedicated Out-of-State Tuition 2020-2021: [27018.14557558]
Pedicated Out-of-State Tuition 2021-2022: [27312.19225982]
----------------------------------------
University of Montana
Model Training Score: 0.9653641002861096
Model Testing Score: 0.9831978413262469
Actual Out-of-State Tuition 2019-2020: 26146
Pedicated Out-of-State Tuition 2020-2021: [27015.46247193]
Pedicated Out-of-State Tuition 2021-2022: [27785.28629542]
----------------------------------------
University of North Carolina at Chapel Hill
Model Training Score: 0.9834818149691794
Model Testing Score: 0.9242577332812036
Actual Out-of-State Tuition 2019-2020: 36225
Pedicated Out-of-State Tuition 2020-2021: [39423.97799024]
Pedicated Out-of-State Tuition 2021-2022: [40714.89266597]
----------------------------------------
University of North Dakota
Model Training Score: 0.7666814903430454
Model Testing Score: -0.35914724117969343

Actual Out-of-State Tuition 2019-2020: 13842
Pedicated Out-of-State Tuition 2020-2021: [16791.03988936]
Pedicated Out-of-State Tuition 2021-2022: [17933.09348684]
----------------------------------------
University of Nebraska - Lincoln
Model Training Score: 0.9736920517848049
Model Testing Score: 0.9751110645574819
Actual Out-of-State Tuition 2019-2020: 25806
Pedicated Out-of-State Tuition 2020-2021: [26437.55832593]
Pedicated Out-of-State Tuition 2021-2022: [27061.81885088]
----------------------------------------
University of New Hampshire
Model Training Score: 0.9554211128292686
Model Testing Score: 0.9090484412133044
Actual Out-of-State Tuition 2019-2020: 35409
Pedicated Out-of-State Tuition 2020-2021: [35066.9353743]
Pedicated Out-of-State Tuition 2021-2022: [34989.20186141]
----------------------------------------
Rutgers, The State University of New Jersey: New Brunswick/Piscataway Campus
Model Training Score: 0.9761080806653626
Model Testing Score: 0.9878587729202826
Actual Out-of-State Tuition 2019-2020: 32189
Pedicated Out-of-State Tuition 2020-2021: [33818.70174025]
Pedicated Out-of-State Tuition 2021-2022: [34753.47992842]
----------------------------------------
University of New Mexico
Model Training Score: 0.9023692034913345
Model Testing Score: 0.9696849121133612
Actual Out-of-State Tuition 2019-2020: 23292
Pedicated Out-of-State Tuition 2020-2021: [23798.73460123]
Pedicated Out-of-State Tuition 2021-2022: [24932.31694012]
----------------------------------------
University of Nevada: Reno
Model Training Score: 0.9214396950679757
Model Testing Score: 0.9299465883745247
Actual Out-of-State Tuition 2019-2020: 23085
Pedicated Out-of-State Tuition 2020-2021: [23173.14863037]
Pedicated Out-of-State Tuition 2021-2022: [24061.98706501]
----------------------------------------
State University of New York at Buffalo
Model Training Score: 0.9534438011628469
Model Testing Score: 0.9342518452978541
Actual Out-of-State Tuition 2019-2020: 28194
Pedicated Out-of-State Tuition 2020-2021: [31485.26250338]
Pedicated Out-of-State Tuition 2021-2022: [31880.18611325]
----------------------------------------
Ohio State University: Columbus Campus
Model Training Score: 0.9408699367918583
Model Testing Score: 0.9315578302734813
Actual Out-of-State Tuition 2019-2020: 32061
Pedicated Out-of-State Tuition 2020-2021: [32650.78829665]
Pedicated Out-of-State Tuition 2021-2022: [32992.93689966]
----------------------------------------
University of Oklahoma
Model Training Score: 0.9584269301974605
Model Testing Score: 0.8567673535496266
Actual Out-of-State Tuition 2019-2020: 27144
Pedicated Out-of-State Tuition 2020-2021: [28632.46585755]
Pedicated Out-of-State Tuition 2021-2022: [28873.74080911]
----------------------------------------
University of Oregon
Model Training Score: 0.9539815623645661
Model Testing Score: 0.9519364685404509
Actual Out-of-State Tuition 2019-2020: 36615
Pedicated Out-of-State Tuition 2020-2021: [38188.78226921]
Pedicated Out-of-State Tuition 2021-2022: [39354.25564641]
----------------------------------------
Penn State University Park
Model Training Score: 0.9658342574518883
Model Testing Score: 0.9528500913130689
Actual Out-of-State Tuition 2019-2020: 35514
Pedicated Out-of-State Tuition 2020-2021: [36295.0576655]
Pedicated Out-of-State Tuition 2021-2022: [36597.44578174]
----------------------------------------
University of Rhode Island
Model Training Score: 0.9190190121333242
Model Testing Score: 0.9073062298873091
Actual Out-of-State Tuition 2019-2020: 31686
Pedicated Out-of-State Tuition 2020-2021: [31457.59113043]
Pedicated Out-of-State Tuition 2021-2022: [31546.89173751]
----------------------------------------
University of South Carolina
Model Training Score: 0.9679037267568661
Model Testing Score: 0.9799684468028872
Actual Out-of-State Tuition 2019-2020: 33928
Pedicated Out-of-State Tuition 2020-2021: [35235.01432813]
Pedicated Out-of-State Tuition 2021-2022: [36120.28602273]
----------------------------------------
University of South Dakota
Model Training Score: 0.9593930712333923
Model Testing Score: 0.9860073227588001
Actual Out-of-State Tuition 2019-2020: 12807
Pedicated Out-of-State Tuition 2020-2021: [13593.74696305]
Pedicated Out-of-State Tuition 2021-2022: [13937.45214286]
----------------------------------------
University of Tennessee: Knoxville
Model Training Score: 0.9783522931928096
Model Testing Score: 0.9562618165158724
Actual Out-of-State Tuition 2019-2020: 31454
Pedicated Out-of-State Tuition 2020-2021: [34696.72791836]
Pedicated Out-of-State Tuition 2021-2022: [37842.95406723]
----------------------------------------
University of Texas at Austin
Model Training Score: 0.9587589774733399
Model Testing Score: 0.9560348860822911
Actual Out-of-State Tuition 2019-2020: 38228
Pedicated Out-of-State Tuition 2020-2021: [39046.0212773]
Pedicated Out-of-State Tuition 2021-2022: [39839.06538816]
----------------------------------------
University of Utah
Model Training Score: 0.9717964052533689
Model Testing Score: 0.9898622380911601
Actual Out-of-State Tuition 2019-2020: 30132
Pedicated Out-of-State Tuition 2020-2021: [31814.20276861]
Pedicated Out-of-State Tuition 2021-2022: [32870.82254547]
----------------------------------------
University of Virginia
Model Training Score: 0.9761017519933826
Model Testing Score: 0.9897799153165464
Actual Out-of-State Tuition 2019-2020: 49970
Pedicated Out-of-State Tuition 2020-2021: [52670.01712481]
Pedicated Out-of-State Tuition 2021-2022: [54227.71663159]
----------------------------------------
University of Vermont
Model Training Score: 0.9717354160522712
Model Testing Score: 0.9887434021608018
Actual Out-of-State Tuition 2019-2020: 43690
Pedicated Out-of-State Tuition 2020-2021: [45237.73731811]
Pedicated Out-of-State Tuition 2021-2022: [46094.88988963]
----------------------------------------
University of Washington
Model Training Score: 0.991146411733956
Model Testing Score: 0.9807953633679202
Actual Out-of-State Tuition 2019-2020: 38166
Pedicated Out-of-State Tuition 2020-2021: [40486.75328437]
Pedicated Out-of-State Tuition 2021-2022: [42788.76167129]
----------------------------------------
University of Wisconsin-Madison
Model Training Score: 0.9267319893253017
Model Testing Score: 0.8160047601550873
Actual Out-of-State Tuition 2019-2020: 37785
Pedicated Out-of-State Tuition 2020-2021: [37969.6332181]
Pedicated Out-of-State Tuition 2021-2022: [37544.35947028]
----------------------------------------
West Virginia University
Model Training Score: 0.978736045221869
Model Testing Score: 0.9269921556731894
Actual Out-of-State Tuition 2019-2020: 25320
Pedicated Out-of-State Tuition 2020-2021: [26219.62330509]
Pedicated Out-of-State Tuition 2021-2022: [26470.80070102]
----------------------------------------
University of Wyoming
Model Training Score: 0.9786718875010398
Model Testing Score: 0.978152119674393
Actual Out-of-State Tuition 2019-2020: 18151
Pedicated Out-of-State Tuition 2020-2021: [18965.98639326]
Pedicated Out-of-State Tuition 2021-2022: [19113.6780355]
----------------------------------------

In [16]:
# Out of State Prediction data to DataFrame
Out_State_Predicted_df = pd.DataFrame.from_dict(out_university)
Out_State_Predicted_df = Out_State_Predicted_df.transpose()
Out_State_Predicted_df

                                                         2020-21       2021-22
University of Alaska Fairbanks                      26671.337140  27070.762371
University of Alabama                               31453.697096  32210.802343
University of Arkansas                              27239.083089  27540.482454
University of Arizona                               39903.148388  39444.489874
University of California: Berkeley                  44120.241050  44148.100324
University of Colorado at Boulder                   39276.353008  39735.560855
University of Connecticut                           42177.308593  42200.426332
University of Delaware                              37082.883166  38763.377152
University of Florida                               29528.791397  31297.200943
University of Georgia                               31934.444970  32376.101432
University of Hawaii at Manoa                       38265.444807  40045.605709
University of Iowa                                  32249.827108  33383.935149
University of Idaho                                 27427.529915  27929.347962
University of Illinois at Urbana-Champaign          34136.892828  34430.783000
Indiana University Bloomington                      38297.339089  40239.214854
University of Kansas                                30311.762779  31442.924614
University of Kentucky                              31998.350798  31861.773690
Louisiana State University and Agricultural and...  32828.399764  36605.848955
University of Massachusetts Amherst                 37064.392451  36958.863777
University of Maryland: College Park                37924.324440  38028.271666
University of Maine                                 32562.776434  33626.301158
University of Michigan                              52343.220806  52635.729986
University of Minnesota: Twin Cities                32477.656026  31927.899715
University of Missouri: Columbia                    29455.628215  29723.210236
University of Mississippi                           27018.145576  27312.192260
University of Montana                               27015.462472  27785.286295
University of North Carolina at Chapel Hill         39423.977990  40714.892666
University of North Dakota                          16791.039889  17933.093487
University of Nebraska - Lincoln                    26437.558326  27061.818851
University of New Hampshire                         35066.935374  34989.201861
Rutgers, The State University of New Jersey: Ne...  33818.701740  34753.479928
University of New Mexico                            23798.734601  24932.316940
University of Nevada: Reno                          23173.148630  24061.987065
State University of New York at Buffalo             31485.262503  31880.186113
Ohio State University: Columbus Campus              32650.788297  32992.936900
University of Oklahoma                              28632.465858  28873.740809
University of Oregon                                38188.782269  39354.255646
Penn State University Park                          36295.057665  36597.445782
University of Rhode Island                          31457.591130  31546.891738
University of South Carolina                        35235.014328  36120.286023
University of South Dakota                          13593.746963  13937.452143
University of Tennessee: Knoxville                  34696.727918  37842.954067
University of Texas at Austin                       39046.021277  39839.065388
University of Utah                                  31814.202769  32870.822545
University of Virginia                              52670.017125  54227.716632
University of Vermont                               45237.737318  46094.889890
University of Washington                            40486.753284  42788.761671
University of Wisconsin-Madison                     37969.633218  37544.359470
West Virginia University                            26219.623305  26470.800701
University of Wyoming                               18965.986393  19113.678036

In [17]:
# Predictions merged with intial dataframe
Out_Tuition_df = pd.merge(Out_State_Tuition_df,Out_State_Predicted_df,how = "inner",left_on="University", right_on=Predicted_df.index)
Out_Tuition_df.columns = ["University","Out_2007_08","Out_2008_09","Out_2009_10","Out_2010_11","Out_2011_12","Out_2012_13",
                         "Out_2013_14","Out_2014_2015","Out_2015_2016","Out_2016_2017","Out_2017_2018","Out_2018_2019","Out_2019_2020",
                         "Out_2020_2021","Out_2021_2022"]
Out_Tuition_df

,University,Out_2007_08,Out_2008_09,Out_2009_10,Out_2010_11,Out_2011_12,Out_2012_13,Out_2013_14,Out_2014_2015,Out_2015_2016,Out_2016_2017,Out_2017_2018,Out_2018_2019,Out_2019_2020,Out_2020_2021,Out_2021_2022
0,University of Alaska Fairbanks,13466,14248,15036,15906,17210,18348,18948,19502,20784,21854,22908,24257,26208,26671.337140,27070.762371
1,University of Alabama,16518,18000,19200,20500,21900,22950,23950,24950,25950,26950,28100,29230,30250,31453.697096,32210.802343
2,University of Arkansas,14492,15278,15445,16000,17606,18434,19075,20302,21826,23168,24308,25168,25872,27239.083089,27540.482454
3,University of Arizona,16271,18665,22572,24597,25509,26231,27073,29421,32600,36017,35307,36386,36738,39903.148388,39444.489874
4,University of California: Berkeley,26784,28264,32418,33819,35713,35752,35742,35850,38139,40167,41942,43176,44007,44120.241050,44148.100324
5,University of Colorado at Boulder,24797,26756,28193,29493,30330,31378,32297,33151,34125,35079,36220,37286,38318,39276.353008,39735.560855
6,University of Connecticut,22786,24050,25584,26880,27566,29074,30970,32880,34908,35858,36948,38098,39894,42177.308593,42200.426332
7,University of Delaware,19400,21126,23408,25408,27462,28772,29932,30692,31420,32250,33150,34310,35710,37082.883166,38763.377152
8,University of Florida,17791,20640,23744,27322,27934,28420,28540,28590,28658,28658,28658,28658,28658,29528.791397,31297.200943
9,University of Georgia,20726,22343,25946,26946,27682,28052,28472,29046,29832,29844,30392,30404,31120,31934.444970,32376.101432
10,University of Hawaii at Manoa,14654,16915,19328,21536,23932,25652,27472,29412,31516,33764,33764,34002,34218,38265.444807,40045.605709
11,University of Iowa,19465,20658,22445,23713,25099,26279,26931,27409,27890,28413,30608,31233,31569,32249.827108,33383.935149
12,University of Idaho,14490,14712,15111,16994,18376,19000,19600,20314,21024,22040,23812,25500,27540,27427.529915,27929.347962
13,University of Illinois at Urbana-Champaign,25216,26024,26336,27238,27980,28664,29132,29646,30786,31320,31988,32574,33352,34136.892828,34430.783000
14,Indiana University Bloomington,22316,24769,26173,27689,29540,31483,32350,33241,33741,34246,34845,35456,36512,38297.339089,40239.214854
15,University of Kansas,17556,18909,20185,21538,22608,23748,24873,25731,26640,28239,26592,27358,28034,30311.762779,31442.924614
16,University of Kentucky,14896,15884,16723,17678,18740,19864,21052,22734,24268,26156,27856,29099,30680,31998.350798,31861.773690
17,Louisiana State University and Agricultural an...,12843,13800,14415,16549,19362,22279,25798,26467,27005,27491,28051,28627,28639,32828.399764,36605.848955
18,University of Massachusetts Amherst,20499,21914,23414,23813,25585,26645,26830,27812,30689,32389,33477,34570,35710,37064.392451,36958.863777
19,University of Maryland: College Park,22208,23076,24156,24831,26026,27287,28347,29720,31144,32045,33606,35216,36891,37924.324440,38028.271666
20,University of Maine,20540,22510,23972,25172,26308,27454,27970,28486,28880,29498,30282,30970,31748,32562.776434,33626.301158
21,University of Michigan,31301,33069,34937,36001,37782,39122,40392,41906,43476,45410,47476,49350,51200,52343.220806,52635.729986
22,University of Minnesota: Twin Cities,21515,14634,15529,16503,18022,18709,19868,20876,22210,23806,26603,30371,33325,32477.656026,31927.899715
23,University of Missouri: Columbia,18755,19558,19682,20516,21784,22440,22569,24460,25166,25892,26506,26949,28290,29455.628215,29723.210236
24,University of Mississippi,11436,12468,13046,13894,14797,16266,17728,19144,20674,22022,23564,24614,25100,27018.145576,27312.192260
25,University of Montana,15504,16425,17794,19172,20099,21077,21719,22372,23048,23669,24871,24959,26146,27015.462472,27785.286295
26,University of North Carolina at Chapel Hill,20988,22295,23609,25286,26834,28445,30122,33428,33673,33916,34588,35170,36225,39423.977990,40714.892666
27,University of North Dakota,14523,15325,15862,16373,16767,17170,17793,18409,18899,19291,20324,20759,13842,16791.039889,17933.093487
28,University of Nebraska - Lincoln,16236,17205,17926,18924,19848,20647,21403,22093,22446,23058,24201,24949,25806,26437.558326,27061.818851
29,University of New Hampshire,24030,25236,26992,27642,28570,28882,29216,29532,30256,31424,32637,33879,35409,35066.935374,34989.201861
30,"Rutgers, The State University of New Jersey: N...",19854,21488,22834,24044,25416,26393,27523,28591,29521,30023,30579,31282,32189,33818.701740,34753.479928
31,University of New Mexico,14942,15708,17234,18691,19999,20688,20688,20652,21304,21936,22037,22586,23292,23798.734601,24932.316940
32,University of Nevada: Reno,14839,15656,17698,18851,19771,20513,20513,20549,20792,21053,21726,22236,23085,23173.148630,24061.987065
33,State University of New York at Buffalo,12478,12545,15036,15546,16932,18609,20366,22291,24541,26814,27338,27769,28194,31485.262503,31880.186113
34,Ohio State University: Columbus Campus,21918,22298,22404,23604,24630,25445,25757,26537,27365,29229,29695,30742,32061,32650.788297,32992.936900
35,University of Oklahoma,15621,17404,17704,18295,19278,20343,21104,22269,23476,25203,26919,27144,27144,28632.465858,28873.740809
36,University of Oregon,19332,19992,23730,25830,27653,28660,29788,30888,32024,33442,34611,35478,36615,38188.782269,39354.255646
37,Penn State University Park,23712,24940,25972,27114,28066,28746,29566,30452,31346,32382,33664,34858,35514,36295.057665,36597.445782
38,University of Rhode Island,23038,24776,26198,27182,27454,28016,28016,28072,28852,28874,30042,30862,31686,31457.591130,31546.891738
39,University of South Carolina,21632,22908,23732,25362,26352,27644,28528,29440,30298,31282,32362,33298,33928,35235.014328,36120.286023
40,University of South Dakota,6631,7148,7892,8259,8924,9650,10104,10104,11337,11688,12020,12425,12807,13593.746963,13937.452143
41,University of Tennessee: Knoxville,17874,18908,20646,22420,25238,27282,29384,30066,30626,30914,31160,31196,31454,34696.727918,37842.954067
42,University of Texas at Austin,24544,27760,30006,31266,32379,33060,33824,34722,34836,35906,36984,37724,38228,39046.021277,39839.065388
43,University of Utah,15662,16601,18193,19841,21389,22642,23736,25267,26022,27039,28067,29215,30132,31814.202769,32870.822545
44,University of Virginia,27515,29798,31326,32902,35898,37336,39844,42184,43082,45058,45922,47562,49970,52670.017125,54227.716632
45,University of Vermont,27938,29682,31454,32630,34424,35612,36646,37844,39130,40364,41356,42516,43690,45237.737318,46094.889890
46,University of Washington,22131,23324,24639,25601,28310,31016,31971,33513,34143,34791,35538,36588,38166,40486.753284,42788.761671
47,University of Wisconsin-Madison,21438,21818,23095,24233,25421,26634,26653,26660,29665,32738,34783,36805,37785,37969.633218,37544.359470
48,West Virginia University,14600,15770,16402,17002,17844,18868,19632,20424,21432,22488,23616,24950,25320,26219.623305,26470.800701
49,University of Wyoming,10394,11031,11697,12237,12855,13428,14124,14876,15631,16215,16827,17490,18151,18965.986393,19113.678036

In [18]:
# Merged In-State and Out of State dataframes
In_Out_Tuition_df = pd.merge(In_State_Tuition_df,Out_Tuition_df,how="inner",on="University")
In_Out_Tuition_df

,University,STATE,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15,...,Out_2012_13,Out_2013_14,Out_2014_2015,Out_2015_2016,Out_2016_2017,Out_2017_2018,Out_2018_2019,Out_2019_2020,Out_2020_2021,Out_2021_2022
0,University of Alaska Fairbanks,AK,4496,4828,5133,5316,5570,5898,5988,6182,...,18348,18948,19502,20784,21854,22908,24257,26208,26671.337140,27070.762371
1,University of Alabama,AL,5700,6400,7000,7900,8600,9200,9450,9826,...,22950,23950,24950,25950,26950,28100,29230,30250,31453.697096,32210.802343
2,University of Arkansas,AR,6038,6400,6459,6768,7174,7553,7818,8210,...,18434,19075,20302,21826,23168,24308,25168,25872,27239.083089,27540.482454
3,University of Arizona,AZ,5037,5531,6855,8237,9299,10035,10391,10957,...,26231,27073,29421,32600,36017,35307,36386,36738,39903.148388,39444.489874
4,University of California: Berkeley,CA,7164,7656,9749,10940,12835,12874,12864,12972,...,35752,35742,35850,38139,40167,41942,43176,44007,44120.241050,44148.100324
5,University of Colorado at Boulder,CO,6635,7278,7932,8511,9152,9482,10529,10789,...,31378,32297,33151,34125,35079,36220,37286,38318,39276.353008,39735.560855
6,University of Connecticut,CT,8842,9338,9886,10416,10670,11242,12022,12700,...,29074,30970,32880,34908,35858,36948,38098,39894,42177.308593,42200.426332
7,University of Delaware,DE,8150,8646,9486,10208,11192,11682,12112,12342,...,28772,29932,30692,31420,32250,33150,34310,35710,37082.883166,38763.377152
8,University of Florida,FL,3370,3790,4373,5045,5657,6143,6263,6313,...,28420,28540,28590,28658,28658,28658,28658,28658,29528.791397,31297.200943
9,University of Georgia,GA,5259,5532,6172,7338,9472,9842,10262,10836,...,28052,28472,29046,29832,29844,30392,30404,31120,31934.444970,32376.101432
10,University of Hawaii at Manoa,HI,5390,6259,7168,8096,9100,9404,9904,10620,...,25652,27472,29412,31516,33764,33764,34002,34218,38265.444807,40045.605709
11,University of Iowa,IA,6293,6544,6824,7417,7765,8057,8061,8079,...,26279,26931,27409,27890,28413,30608,31233,31569,32249.827108,33383.935149
12,University of Idaho,ID,4410,4632,4932,5402,5856,6212,6524,6784,...,19000,19600,20314,21024,22040,23812,25500,27540,27427.529915,27929.347962
13,University of Illinois at Urbana-Champaign,IL,11130,12240,12528,13096,13838,14522,14750,15020,...,28664,29132,29646,30786,31320,31988,32574,33352,34136.892828,34430.783000
14,Indiana University Bloomington,IN,7837,8231,8613,9028,9524,10033,10209,10388,...,31483,32350,33241,33741,34246,34845,35456,36512,38297.339089,40239.214854
15,University of Kansas,KS,7146,7705,8206,8733,9222,9678,10107,10448,...,23748,24873,25731,26640,28239,26592,27358,28034,30311.762779,31442.924614
16,University of Kentucky,KY,7096,7736,8123,8610,9128,9676,9966,10464,...,19864,21052,22734,24268,26156,27856,29099,30680,31998.350798,31861.773690
17,Louisiana State University and Agricultural an...,LA,4543,5086,5233,5764,6354,7003,7880,8750,...,22279,25798,26467,27005,27491,28051,28627,28639,32828.399764,36605.848955
18,University of Massachusetts Amherst,MA,9924,10417,11917,11917,12797,13230,13415,13443,...,26645,26830,27812,30689,32389,33477,34570,35710,37064.392451,36958.863777
19,University of Maryland: College Park,MD,7969,8005,8053,8416,8655,8908,9161,9427,...,27287,28347,29720,31144,32045,33606,35216,36891,37924.324440,38028.271666
20,University of Maine,ME,8330,9100,9626,10142,10588,10594,10600,10606,...,27454,27970,28486,28880,29498,30282,30970,31748,32562.776434,33626.301158
21,University of Michigan,MI,10447,11037,11848,11837,12634,12994,13142,13486,...,39122,40392,41906,43476,45410,47476,49350,51200,52343.220806,52635.729986
22,University of Minnesota: Twin Cities,MN,9885,10634,11287,12203,13022,13459,13618,13626,...,18709,19868,20876,22210,23806,26603,30371,33325,32477.656026,31927.899715
23,University of Missouri: Columbia,MO,8099,8485,8501,8501,8989,9257,9415,9433,...,22440,22569,24460,25166,25892,26506,26949,28290,29455.628215,29723.210236
24,University of Mississippi,MS,4932,5107,5106,5439,5792,6282,6760,7096,...,16266,17728,19144,20674,22022,23564,24614,25100,27018.145576,27312.192260
25,University of Montana,MT,5141,5150,5330,5476,5722,5985,6045,6099,...,21077,21719,22372,23048,23669,24871,24959,26146,27015.462472,27785.286295
26,University of North Carolina at Chapel Hill,NC,5340,5397,5625,6671,7008,7693,8340,8336,...,28445,30122,33428,33673,33916,34588,35170,36225,39423.977990,40714.892666
27,University of North Dakota,ND,6130,6513,6726,6934,7092,7254,7508,7741,...,17170,17793,18409,18899,19291,20324,20759,13842,16791.039889,17933.093487
28,University of Nebraska - Lincoln,NE,6216,6585,6857,7224,7563,7897,8075,8070,...,20647,21403,22093,22446,23058,24201,24949,25806,26437.558326,27061.818851
29,University of New Hampshire,NH,11070,11756,12743,13672,15250,16422,16496,16552,...,28882,29216,29532,30256,31424,32637,33879,35409,35066.935374,34989.201861
30,"Rutgers, The State University of New Jersey: N...",NJ,10686,11540,11886,12582,12754,13073,13499,13813,...,26393,27523,28591,29521,30023,30579,31282,32189,33818.701740,34753.479928
31,University of New Mexico,NM,4571,4834,5101,5506,5809,6049,6447,6447,...,20688,20688,20652,21304,21936,22037,22586,23292,23798.734601,24932.316940
32,University of Nevada: Reno,NV,4029,4561,4901,5561,6176,6603,6603,6639,...,20513,20513,20549,20792,21053,21726,22236,23085,23173.148630,24061.987065
33,State University of New York at Buffalo,NY,6218,6285,7013,7136,7482,7989,8426,8871,...,18609,20366,22291,24541,26814,27338,27769,28194,31485.262503,31880.186113
34,Ohio State University: Columbus Campus,OH,8676,8679,8726,9420,9735,10037,10037,10037,...,25445,25757,26537,27365,29229,29695,30742,32061,32650.788297,32992.936900
35,University of Oklahoma,OK,6507,7423,7483,7864,8325,8706,8915,9495,...,20343,21104,22269,23476,25203,26919,27144,27144,28632.465858,28873.740809
36,University of Oregon,OR,6168,6435,7428,8190,8789,9310,9763,9918,...,28660,29788,30888,32024,33442,34611,35478,36615,38188.782269,39354.255646
37,Penn State University Park,PA,13639,13706,14416,15250,15984,16444,16992,17502,...,28746,29566,30452,31346,32382,33664,34858,35514,36295.057665,36597.445782
38,University of Rhode Island,RI,8184,8678,9528,10476,11366,12450,12450,12506,...,28016,28016,28072,28852,28874,30042,30862,31686,31457.591130,31546.891738
39,University of South Carolina,SC,8346,8838,9156,9786,10168,10488,10816,11158,...,27644,28528,29440,30298,31282,32362,33298,33928,35235.014328,36120.286023
40,University of South Dakota,SD,5393,5828,6468,6762,7209,7704,8022,8022,...,9650,10104,10104,11337,11688,12020,12425,12807,13593.746963,13937.452143
41,University of Tennessee: Knoxville,TN,5932,6250,6855,7382,8396,9092,11194,11876,...,27282,29384,30066,30626,30914,31160,31196,31454,34696.727918,37842.954067
42,University of Texas at Austin,TX,7670,8532,8930,9416,9792,9790,9790,9798,...,33060,33824,34722,34836,35906,36984,37724,38228,39046.021277,39839.065388
43,University of Utah,UT,4987,5285,5746,6274,6763,7139,7457,7935,...,22642,23736,25267,26022,27039,28067,29215,30132,31814.202769,32870.822545
44,University of Virginia,VA,8500,9505,9672,10628,11576,12006,12458,12998,...,37336,39844,42184,43082,45058,45922,47562,49970,52670.017125,54227.716632
45,University of Vermont,VT,12054,12844,13554,14066,14784,15284,15718,16196,...,35612,36646,37844,39130,40364,41356,42516,43690,45237.737318,46094.889890
46,University of Washington,WA,6385,6907,7964,8973,10826,12383,12397,12394,...,31016,31971,33513,34143,34791,35538,36588,38166,40486.753284,42788.761671
47,University of Wisconsin-Madison,WI,7188,7568,8310,8983,9671,10384,10403,10410,...,26634,26653,26660,29665,32738,34783,36805,37785,37969.633218,37544.359470
48,West Virginia University,WV,4722,5100,5304,5406,5674,6090,6456,6960,...,18868,19632,20424,21432,22488,23616,24950,25320,26219.623305,26470.800701
49,University of Wyoming,WY,3554,3621,3726,3927,4125,4278,4404,4646,...,13428,14124,14876,15631,16215,16827,17490,18151,18965.986393,19113.678036

In [19]:
# State and intials dictionary to dataframe
states = {"AL":"Alabama","AK":"Alaska","AZ":"Arizona","AR":"Arkansas","CA":"California","CO":"Colorado","CT":"Connecticut",
          "DE":"Delaware","FL":"Florida","GA":"Georgia","HI":"Hawaii","ID":"Idaho","IL":"Illinois","IN":"Indiana",
          "IA":"Iowa","KS":"Kansas","KY":"Kentucky","LA":"Louisiana","ME":"Maine","MD":"Maryland","MA":"Massachusetts",
          "MI":"Michigan","MN":"Minnesota","MS":"Mississippi","MO":"Missouri","MT":"Montana","NE":"Nebraska","NV":"Nevada",
          "NH":"New Hampshire","NJ":"New Jersey","NM":"New Mexico","NY":"New York","NC":"North Carolina","ND":"North Dakota",
          "OH":"Ohio","OK":"Oklahoma","OR":"Oregon","PA":"Pennsylvania","RI":"Rhode Island","SC":"South Carolina",
          "SD":"South Dakota","TN":"Tennessee","TX":"Texas","UT":"Utah","VT":"Vermont","VA":"Virginia","WA":"Washington",
          "WV":"West Virginia","WI":"Wisconsin","WY":"Wyoming"}

stateInitial = pd.DataFrame(list(states.items()),columns = ['STATE','STATE_NAME']) 
stateInitial

   STATE      STATE_NAME
0     AL         Alabama
1     AK          Alaska
2     AZ         Arizona
3     AR        Arkansas
4     CA      California
5     CO        Colorado
6     CT     Connecticut
7     DE        Delaware
8     FL         Florida
9     GA         Georgia
10    HI          Hawaii
11    ID           Idaho
12    IL        Illinois
13    IN         Indiana
14    IA            Iowa
15    KS          Kansas
16    KY        Kentucky
17    LA       Louisiana
18    ME           Maine
19    MD        Maryland
20    MA   Massachusetts
21    MI        Michigan
22    MN       Minnesota
23    MS     Mississippi
24    MO        Missouri
25    MT         Montana
26    NE        Nebraska
27    NV          Nevada
28    NH   New Hampshire
29    NJ      New Jersey
30    NM      New Mexico
31    NY        New York
32    NC  North Carolina
33    ND    North Dakota
34    OH            Ohio
35    OK        Oklahoma
36    OR          Oregon
37    PA    Pennsylvania
38    RI    Rhode Island
39    SC  South Carolina
40    SD    South Dakota
41    TN       Tennessee
42    TX           Texas
43    UT            Utah
44    VT         Vermont
45    VA        Virginia
46    WA      Washington
47    WV   West Virginia
48    WI       Wisconsin
49    WY         Wyoming

In [20]:
# final Tuition DataFrame with merged State name 
Final_Tuition_df = pd.merge(In_Out_Tuition_df,stateInitial,how = "inner")
Final_Tuition_df

,University,STATE,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15,...,Out_2013_14,Out_2014_2015,Out_2015_2016,Out_2016_2017,Out_2017_2018,Out_2018_2019,Out_2019_2020,Out_2020_2021,Out_2021_2022,STATE_NAME
0,University of Alaska Fairbanks,AK,4496,4828,5133,5316,5570,5898,5988,6182,...,18948,19502,20784,21854,22908,24257,26208,26671.337140,27070.762371,Alaska
1,University of Alabama,AL,5700,6400,7000,7900,8600,9200,9450,9826,...,23950,24950,25950,26950,28100,29230,30250,31453.697096,32210.802343,Alabama
2,University of Arkansas,AR,6038,6400,6459,6768,7174,7553,7818,8210,...,19075,20302,21826,23168,24308,25168,25872,27239.083089,27540.482454,Arkansas
3,University of Arizona,AZ,5037,5531,6855,8237,9299,10035,10391,10957,...,27073,29421,32600,36017,35307,36386,36738,39903.148388,39444.489874,Arizona
4,University of California: Berkeley,CA,7164,7656,9749,10940,12835,12874,12864,12972,...,35742,35850,38139,40167,41942,43176,44007,44120.241050,44148.100324,California
5,University of Colorado at Boulder,CO,6635,7278,7932,8511,9152,9482,10529,10789,...,32297,33151,34125,35079,36220,37286,38318,39276.353008,39735.560855,Colorado
6,University of Connecticut,CT,8842,9338,9886,10416,10670,11242,12022,12700,...,30970,32880,34908,35858,36948,38098,39894,42177.308593,42200.426332,Connecticut
7,University of Delaware,DE,8150,8646,9486,10208,11192,11682,12112,12342,...,29932,30692,31420,32250,33150,34310,35710,37082.883166,38763.377152,Delaware
8,University of Florida,FL,3370,3790,4373,5045,5657,6143,6263,6313,...,28540,28590,28658,28658,28658,28658,28658,29528.791397,31297.200943,Florida
9,University of Georgia,GA,5259,5532,6172,7338,9472,9842,10262,10836,...,28472,29046,29832,29844,30392,30404,31120,31934.444970,32376.101432,Georgia
10,University of Hawaii at Manoa,HI,5390,6259,7168,8096,9100,9404,9904,10620,...,27472,29412,31516,33764,33764,34002,34218,38265.444807,40045.605709,Hawaii
11,University of Iowa,IA,6293,6544,6824,7417,7765,8057,8061,8079,...,26931,27409,27890,28413,30608,31233,31569,32249.827108,33383.935149,Iowa
12,University of Idaho,ID,4410,4632,4932,5402,5856,6212,6524,6784,...,19600,20314,21024,22040,23812,25500,27540,27427.529915,27929.347962,Idaho
13,University of Illinois at Urbana-Champaign,IL,11130,12240,12528,13096,13838,14522,14750,15020,...,29132,29646,30786,31320,31988,32574,33352,34136.892828,34430.783000,Illinois
14,Indiana University Bloomington,IN,7837,8231,8613,9028,9524,10033,10209,10388,...,32350,33241,33741,34246,34845,35456,36512,38297.339089,40239.214854,Indiana
15,University of Kansas,KS,7146,7705,8206,8733,9222,9678,10107,10448,...,24873,25731,26640,28239,26592,27358,28034,30311.762779,31442.924614,Kansas
16,University of Kentucky,KY,7096,7736,8123,8610,9128,9676,9966,10464,...,21052,22734,24268,26156,27856,29099,30680,31998.350798,31861.773690,Kentucky
17,Louisiana State University and Agricultural an...,LA,4543,5086,5233,5764,6354,7003,7880,8750,...,25798,26467,27005,27491,28051,28627,28639,32828.399764,36605.848955,Louisiana
18,University of Massachusetts Amherst,MA,9924,10417,11917,11917,12797,13230,13415,13443,...,26830,27812,30689,32389,33477,34570,35710,37064.392451,36958.863777,Massachusetts
19,University of Maryland: College Park,MD,7969,8005,8053,8416,8655,8908,9161,9427,...,28347,29720,31144,32045,33606,35216,36891,37924.324440,38028.271666,Maryland
20,University of Maine,ME,8330,9100,9626,10142,10588,10594,10600,10606,...,27970,28486,28880,29498,30282,30970,31748,32562.776434,33626.301158,Maine
21,University of Michigan,MI,10447,11037,11848,11837,12634,12994,13142,13486,...,40392,41906,43476,45410,47476,49350,51200,52343.220806,52635.729986,Michigan
22,University of Minnesota: Twin Cities,MN,9885,10634,11287,12203,13022,13459,13618,13626,...,19868,20876,22210,23806,26603,30371,33325,32477.656026,31927.899715,Minnesota
23,University of Missouri: Columbia,MO,8099,8485,8501,8501,8989,9257,9415,9433,...,22569,24460,25166,25892,26506,26949,28290,29455.628215,29723.210236,Missouri
24,University of Mississippi,MS,4932,5107,5106,5439,5792,6282,6760,7096,...,17728,19144,20674,22022,23564,24614,25100,27018.145576,27312.192260,Mississippi
25,University of Montana,MT,5141,5150,5330,5476,5722,5985,6045,6099,...,21719,22372,23048,23669,24871,24959,26146,27015.462472,27785.286295,Montana
26,University of North Carolina at Chapel Hill,NC,5340,5397,5625,6671,7008,7693,8340,8336,...,30122,33428,33673,33916,34588,35170,36225,39423.977990,40714.892666,North Carolina
27,University of North Dakota,ND,6130,6513,6726,6934,7092,7254,7508,7741,...,17793,18409,18899,19291,20324,20759,13842,16791.039889,17933.093487,North Dakota
28,University of Nebraska - Lincoln,NE,6216,6585,6857,7224,7563,7897,8075,8070,...,21403,22093,22446,23058,24201,24949,25806,26437.558326,27061.818851,Nebraska
29,University of New Hampshire,NH,11070,11756,12743,13672,15250,16422,16496,16552,...,29216,29532,30256,31424,32637,33879,35409,35066.935374,34989.201861,New Hampshire
30,"Rutgers, The State University of New Jersey: N...",NJ,10686,11540,11886,12582,12754,13073,13499,13813,...,27523,28591,29521,30023,30579,31282,32189,33818.701740,34753.479928,New Jersey
31,University of New Mexico,NM,4571,4834,5101,5506,5809,6049,6447,6447,...,20688,20652,21304,21936,22037,22586,23292,23798.734601,24932.316940,New Mexico
32,University of Nevada: Reno,NV,4029,4561,4901,5561,6176,6603,6603,6639,...,20513,20549,20792,21053,21726,22236,23085,23173.148630,24061.987065,Nevada
33,State University of New York at Buffalo,NY,6218,6285,7013,7136,7482,7989,8426,8871,...,20366,22291,24541,26814,27338,27769,28194,31485.262503,31880.186113,New York
34,Ohio State University: Columbus Campus,OH,8676,8679,8726,9420,9735,10037,10037,10037,...,25757,26537,27365,29229,29695,30742,32061,32650.788297,32992.936900,Ohio
35,University of Oklahoma,OK,6507,7423,7483,7864,8325,8706,8915,9495,...,21104,22269,23476,25203,26919,27144,27144,28632.465858,28873.740809,Oklahoma
36,University of Oregon,OR,6168,6435,7428,8190,8789,9310,9763,9918,...,29788,30888,32024,33442,34611,35478,36615,38188.782269,39354.255646,Oregon
37,Penn State University Park,PA,13639,13706,14416,15250,15984,16444,16992,17502,...,29566,30452,31346,32382,33664,34858,35514,36295.057665,36597.445782,Pennsylvania
38,University of Rhode Island,RI,8184,8678,9528,10476,11366,12450,12450,12506,...,28016,28072,28852,28874,30042,30862,31686,31457.591130,31546.891738,Rhode Island
39,University of South Carolina,SC,8346,8838,9156,9786,10168,10488,10816,11158,...,28528,29440,30298,31282,32362,33298,33928,35235.014328,36120.286023,South Carolina
40,University of South Dakota,SD,5393,5828,6468,6762,7209,7704,8022,8022,...,10104,10104,11337,11688,12020,12425,12807,13593.746963,13937.452143,South Dakota
41,University of Tennessee: Knoxville,TN,5932,6250,6855,7382,8396,9092,11194,11876,...,29384,30066,30626,30914,31160,31196,31454,34696.727918,37842.954067,Tennessee
42,University of Texas at Austin,TX,7670,8532,8930,9416,9792,9790,9790,9798,...,33824,34722,34836,35906,36984,37724,38228,39046.021277,39839.065388,Texas
43,University of Utah,UT,4987,5285,5746,6274,6763,7139,7457,7935,...,23736,25267,26022,27039,28067,29215,30132,31814.202769,32870.822545,Utah
44,University of Virginia,VA,8500,9505,9672,10628,11576,12006,12458,12998,...,39844,42184,43082,45058,45922,47562,49970,52670.017125,54227.716632,Virginia
45,University of Vermont,VT,12054,12844,13554,14066,14784,15284,15718,16196,...,36646,37844,39130,40364,41356,42516,43690,45237.737318,46094.889890,Vermont
46,University of Washington,WA,6385,6907,7964,8973,10826,12383,12397,12394,...,31971,33513,34143,34791,35538,36588,38166,40486.753284,42788.761671,Washington
47,University of Wisconsin-Madison,WI,7188,7568,8310,8983,9671,10384,10403,10410,...,26653,26660,29665,32738,34783,36805,37785,37969.633218,37544.359470,Wisconsin
48,West Virginia University,WV,4722,5100,5304,5406,5674,6090,6456,6960,...,19632,20424,21432,22488,23616,24950,25320,26219.623305,26470.800701,West Virginia
49,University of Wyoming,WY,3554,3621,3726,3927,4125,4278,4404,4646,...,14124,14876,15631,16215,16827,17490,18151,18965.986393,19113.678036,Wyoming

In [21]:
#Final Tuition Dictionary by State
Tuition_dict = {}
for i in Final_Tuition_df.index:
    State = Final_Tuition_df['STATE'][i]
    STATE_NAME = Final_Tuition_df['STATE_NAME'][i]
    Univ = Final_Tuition_df['University'][i]
    
    In_Cost_2007 = Final_Tuition_df['2007-08'][i]
    In_Cost_2008 = Final_Tuition_df['2008-09'][i]
    In_Cost_2009 = Final_Tuition_df['2009-10'][i]
    In_Cost_2010 = Final_Tuition_df['2010-11'][i]
    In_Cost_2011 = Final_Tuition_df['2011-12'][i]
    In_Cost_2012 = Final_Tuition_df['2012-13'][i]
    In_Cost_2013 = Final_Tuition_df['2013-14'][i]
    In_Cost_2014 = Final_Tuition_df['2014-15'][i]
    In_Cost_2015 = Final_Tuition_df['2015-16'][i]
    In_Cost_2016 = Final_Tuition_df['2016-17'][i]
    In_Cost_2017 = Final_Tuition_df['2017-18'][i]
    In_Cost_2018 = Final_Tuition_df['2018-19'][i]
    In_Cost_2019 = Final_Tuition_df['2019-20'][i]
    In_Cost_2020 = round(Final_Tuition_df['2020-21'][i])
    In_Cost_2021 = round(Final_Tuition_df['2021-22'][i])
    
    Out_Cost_2007 = Final_Tuition_df["Out_2007_08"][i]
    Out_Cost_2008 = Final_Tuition_df['Out_2008_09'][i]
    Out_Cost_2009 = Final_Tuition_df['Out_2009_10'][i]
    Out_Cost_2010 = Final_Tuition_df['Out_2010_11'][i]
    Out_Cost_2011 = Final_Tuition_df['Out_2011_12'][i]
    Out_Cost_2012 = Final_Tuition_df['Out_2012_13'][i]
    Out_Cost_2013 = Final_Tuition_df['Out_2013_14'][i]
    Out_Cost_2014 = Final_Tuition_df['Out_2014_2015'][i]
    Out_Cost_2015 = Final_Tuition_df['Out_2015_2016'][i]
    Out_Cost_2016 = Final_Tuition_df['Out_2016_2017'][i]
    Out_Cost_2017 = Final_Tuition_df['Out_2017_2018'][i]
    Out_Cost_2018 = Final_Tuition_df['Out_2018_2019'][i]
    Out_Cost_2019 = Final_Tuition_df['Out_2019_2020'][i]
    Out_Cost_2020 = round(Final_Tuition_df['Out_2020_2021'][i])
    Out_Cost_2021 = round(Final_Tuition_df['Out_2021_2022'][i])
        
                
    Tuition_dict[State] = {"State_ID" : State,
                           "State_name" : STATE_NAME,
                           "University":Univ,
                           "In_State_Tuition_2007-2008":In_Cost_2007,
                           "In_State_Tuition_2008-2009":In_Cost_2008,
                           "In_State_Tuition_2009-2010":In_Cost_2009,
                           "In_State_Tuition_2010-2011":In_Cost_2010,
                           "In_State_Tuition_2011-2012":In_Cost_2011,
                           "In_State_Tuition_2012-2013":In_Cost_2012,
                           "In_State_Tuition_2013-2014":In_Cost_2013,
                           "In_State_Tuition_2014-2015":In_Cost_2014,
                           "In_State_Tuition_2015-2016":In_Cost_2015,
                           "In_State_Tuition_2016-2017":In_Cost_2016,
                           "In_State_Tuition_2017-2018":In_Cost_2017,
                           "In_State_Tuition_2018-2019":In_Cost_2018,
                           "In_State_Tuition_2019-2020":In_Cost_2019,
                           "In_State_Tuition_2020-2021":In_Cost_2020,
                           "In_State_Tuition_2021-2022":In_Cost_2021,
                           "Out_of_State_Tuition_2007-2008":Out_Cost_2007,
                           "Out_of_State_Tuition_2008-2009":Out_Cost_2008,
                           "Out_of_State_Tuition_2009-2010":Out_Cost_2009,
                           "Out_of_State_Tuition_2010-2011":Out_Cost_2010,
                           "Out_of_State_Tuition_2011-2012":Out_Cost_2011,
                           "Out_of_State_Tuition_2012-2013":Out_Cost_2012,
                           "Out_of_State_Tuition_2013-2014":Out_Cost_2013,
                           "Out_of_State_Tuition_2014-2015":Out_Cost_2014,
                           "Out_of_State_Tuition_2015-2016":Out_Cost_2015,
                           "Out_of_State_Tuition_2016-2017":Out_Cost_2016,
                           "Out_of_State_Tuition_2017-2018":Out_Cost_2017,
                           "Out_of_State_Tuition_2018-2019":Out_Cost_2018,
                           "Out_of_State_Tuition_2019-2020":Out_Cost_2019,
                           "Out_of_State_Tuition_2020-2021":Out_Cost_2020,
                           "Out_of_State_Tuition_2021-2022":Out_Cost_2021}    

Tuition_dict

{'AK': {'State_ID': 'AK',
  'State_name': 'Alaska',
  'University': 'University of Alaska Fairbanks',
  'In_State_Tuition_2007-2008': 4496,
  'In_State_Tuition_2008-2009': 4828,
  'In_State_Tuition_2009-2010': 5133,
  'In_State_Tuition_2010-2011': 5316,
  'In_State_Tuition_2011-2012': 5570,
  'In_State_Tuition_2012-2013': 5898,
  'In_State_Tuition_2013-2014': 5988,
  'In_State_Tuition_2014-2015': 6182,
  'In_State_Tuition_2015-2016': 6804,
  'In_State_Tuition_2016-2017': 7184,
  'In_State_Tuition_2017-2018': 7518,
  'In_State_Tuition_2018-2019': 8087.0,
  'In_State_Tuition_2019-2020': 8538,
  'In_State_Tuition_2020-2021': 8657.0,
  'In_State_Tuition_2021-2022': 8552.0,
  'Out_of_State_Tuition_2007-2008': 13466,
  'Out_of_State_Tuition_2008-2009': 14248,
  'Out_of_State_Tuition_2009-2010': 15036,
  'Out_of_State_Tuition_2010-2011': 15906,
  'Out_of_State_Tuition_2011-2012': 17210,
  'Out_of_State_Tuition_2012-2013': 18348,
  'Out_of_State_Tuition_2013-2014': 18948,
  'Out_of_State_Tuition_2014-2015': 19502,
  'Out_of_State_Tuition_2015-2016': 20784,
  'Out_of_State_Tuition_2016-2017': 21854,
  'Out_of_State_Tuition_2017-2018': 22908,
  'Out_of_State_Tuition_2018-2019': 24257,
  'Out_of_State_Tuition_2019-2020': 26208,
  'Out_of_State_Tuition_2020-2021': 26671.0,
  'Out_of_State_Tuition_2021-2022': 27071.0},
 'AL': {'State_ID': 'AL',
  'State_name': 'Alabama',
  'University': 'University of Alabama',
  'In_State_Tuition_2007-2008': 5700,
  'In_State_Tuition_2008-2009': 6400,
  'In_State_Tuition_2009-2010': 7000,
  'In_State_Tuition_2010-2011': 7900,
  'In_State_Tuition_2011-2012': 8600,
  'In_State_Tuition_2012-2013': 9200,
  'In_State_Tuition_2013-2014': 9450,
  'In_State_Tuition_2014-2015': 9826,
  'In_State_Tuition_2015-2016': 10170,
  'In_State_Tuition_2016-2017': 10470,
  'In_State_Tuition_2017-2018': 10780,
  'In_State_Tuition_2018-2019': 10780.0,
  'In_State_Tuition_2019-2020': 10780,
  'In_State_Tuition_2020-2021': 11643.0,
  'In_State_Tuition_2021-2022': 12414.0,
  'Out_of_State_Tuition_2007-2008': 16518,
  'Out_of_State_Tuition_2008-2009': 18000,
  'Out_of_State_Tuition_2009-2010': 19200,
  'Out_of_State_Tuition_2010-2011': 20500,
  'Out_of_State_Tuition_2011-2012': 21900,
  'Out_of_State_Tuition_2012-2013': 22950,
  'Out_of_State_Tuition_2013-2014': 23950,
  'Out_of_State_Tuition_2014-2015': 24950,
  'Out_of_State_Tuition_2015-2016': 25950,
  'Out_of_State_Tuition_2016-2017': 26950,
  'Out_of_State_Tuition_2017-2018': 28100,
  'Out_of_State_Tuition_2018-2019': 29230,
  'Out_of_State_Tuition_2019-2020': 30250,
  'Out_of_State_Tuition_2020-2021': 31454.0,
  'Out_of_State_Tuition_2021-2022': 32211.0},
 'AR': {'State_ID': 'AR',
  'State_name': 'Arkansas',
  'University': 'University of Arkansas',
  'In_State_Tuition_2007-2008': 6038,
  'In_State_Tuition_2008-2009': 6400,
  'In_State_Tuition_2009-2010': 6459,
  'In_State_Tuition_2010-2011': 6768,
  'In_State_Tuition_2011-2012': 7174,
  'In_State_Tuition_2012-2013': 7553,
  'In_State_Tuition_2013-2014': 7818,
  'In_State_Tuition_2014-2015': 8210,
  'In_State_Tuition_2015-2016': 8522,
  'In_State_Tuition_2016-2017': 8820,
  'In_State_Tuition_2017-2018': 9062,
  'In_State_Tuition_2018-2019': 9130.0,
  'In_State_Tuition_2019-2020': 9384,
  'In_State_Tuition_2020-2021': 9936.0,
  'In_State_Tuition_2021-2022': 10193.0,
  'Out_of_State_Tuition_2007-2008': 14492,
  'Out_of_State_Tuition_2008-2009': 15278,
  'Out_of_State_Tuition_2009-2010': 15445,
  'Out_of_State_Tuition_2010-2011': 16000,
  'Out_of_State_Tuition_2011-2012': 17606,
  'Out_of_State_Tuition_2012-2013': 18434,
  'Out_of_State_Tuition_2013-2014': 19075,
  'Out_of_State_Tuition_2014-2015': 20302,
  'Out_of_State_Tuition_2015-2016': 21826,
  'Out_of_State_Tuition_2016-2017': 23168,
  'Out_of_State_Tuition_2017-2018': 24308,
  'Out_of_State_Tuition_2018-2019': 25168,
  'Out_of_State_Tuition_2019-2020': 25872,
  'Out_of_State_Tuition_2020-2021': 27239.0,
  'Out_of_State_Tuition_2021-2022': 27540.0},
 'AZ': {'State_ID': 'AZ',
  'State_name': 'Arizona',
  'University': 'University of Arizona',
  'In_State_Tuition_2007-2008': 5037,
  'In_State_Tuition_2008-2009': 5531,
  'In_State_Tuition_2009-2010': 6855,
  'In_State_Tuition_2010-2011': 8237,
  'In_State_Tuition_2011-2012': 9299,
  'In_State_Tuition_2012-2013': 10035,
  'In_State_Tuition_2013-2014': 10391,
  'In_State_Tuition_2014-2015': 10957,
  'In_State_Tuition_2015-2016': 11403,
  'In_State_Tuition_2016-2017': 11769,
  'In_State_Tuition_2017-2018': 11877,
  'In_State_Tuition_2018-2019': 12487.0,
  'In_State_Tuition_2019-2020': 12711,
  'In_State_Tuition_2020-2021': 13753.0,
  'In_State_Tuition_2021-2022': 14804.0,
  'Out_of_State_Tuition_2007-2008': 16271,
  'Out_of_State_Tuition_2008-2009': 18665,
  'Out_of_State_Tuition_2009-2010': 22572,
  'Out_of_State_Tuition_2010-2011': 24597,
  'Out_of_State_Tuition_2011-2012': 25509,
  'Out_of_State_Tuition_2012-2013': 26231,
  'Out_of_State_Tuition_2013-2014': 27073,
  'Out_of_State_Tuition_2014-2015': 29421,
  'Out_of_State_Tuition_2015-2016': 32600,
  'Out_of_State_Tuition_2016-2017': 36017,
  'Out_of_State_Tuition_2017-2018': 35307,
  'Out_of_State_Tuition_2018-2019': 36386,
  'Out_of_State_Tuition_2019-2020': 36738,
  'Out_of_State_Tuition_2020-2021': 39903.0,
  'Out_of_State_Tuition_2021-2022': 39444.0},
 'CA': {'State_ID': 'CA',
  'State_name': 'California',
  'University': 'University of California: Berkeley',
  'In_State_Tuition_2007-2008': 7164,
  'In_State_Tuition_2008-2009': 7656,
  'In_State_Tuition_2009-2010': 9749,
  'In_State_Tuition_2010-2011': 10940,
  'In_State_Tuition_2011-2012': 12835,
  'In_State_Tuition_2012-2013': 12874,
  'In_State_Tuition_2013-2014': 12864,
  'In_State_Tuition_2014-2015': 12972,
  'In_State_Tuition_2015-2016': 13431,
  'In_State_Tuition_2016-2017': 13485,
  'In_State_Tuition_2017-2018': 13928,
  'In_State_Tuition_2018-2019': 14184.0,
  'In_State_Tuition_2019-2020': 14253,
  'In_State_Tuition_2020-2021': 14813.0,
  'In_State_Tuition_2021-2022': 16087.0,
  'Out_of_State_Tuition_2007-2008': 26784,
  'Out_of_State_Tuition_2008-2009': 28264,
  'Out_of_State_Tuition_2009-2010': 32418,
  'Out_of_State_Tuition_2010-2011': 33819,
  'Out_of_State_Tuition_2011-2012': 35713,
  'Out_of_State_Tuition_2012-2013': 35752,
  'Out_of_State_Tuition_2013-2014': 35742,
  'Out_of_State_Tuition_2014-2015': 35850,
  'Out_of_State_Tuition_2015-2016': 38139,
  'Out_of_State_Tuition_2016-2017': 40167,
  'Out_of_State_Tuition_2017-2018': 41942,
  'Out_of_State_Tuition_2018-2019': 43176,
  'Out_of_State_Tuition_2019-2020': 44007,
  'Out_of_State_Tuition_2020-2021': 44120.0,
  'Out_of_State_Tuition_2021-2022': 44148.0},
 'CO': {'State_ID': 'CO',
  'State_name': 'Colorado',
  'University': 'University of Colorado at Boulder',
  'In_State_Tuition_2007-2008': 6635,
  'In_State_Tuition_2008-2009': 7278,
  'In_State_Tuition_2009-2010': 7932,
  'In_State_Tuition_2010-2011': 8511,
  'In_State_Tuition_2011-2012': 9152,
  'In_State_Tuition_2012-2013': 9482,
  'In_State_Tuition_2013-2014': 10529,
  'In_State_Tuition_2014-2015': 10789,
  'In_State_Tuition_2015-2016': 11091,
  'In_State_Tuition_2016-2017': 11531,
  'In_State_Tuition_2017-2018': 12086,
  'In_State_Tuition_2018-2019': 12532.0,
  'In_State_Tuition_2019-2020': 12500,
  'In_State_Tuition_2020-2021': 13323.0,
  'In_State_Tuition_2021-2022': 13845.0,
  'Out_of_State_Tuition_2007-2008': 24797,
  'Out_of_State_Tuition_2008-2009': 26756,
  'Out_of_State_Tuition_2009-2010': 28193,
  'Out_of_State_Tuition_2010-2011': 29493,
  'Out_of_State_Tuition_2011-2012': 30330,
  'Out_of_State_Tuition_2012-2013': 31378,
  'Out_of_State_Tuition_2013-2014': 32297,
  'Out_of_State_Tuition_2014-2015': 33151,
  'Out_of_State_Tuition_2015-2016': 34125,
  'Out_of_State_Tuition_2016-2017': 35079,
  'Out_of_State_Tuition_2017-2018': 36220,
  'Out_of_State_Tuition_2018-2019': 37286,
  'Out_of_State_Tuition_2019-2020': 38318,
  'Out_of_State_Tuition_2020-2021': 39276.0,
  'Out_of_State_Tuition_2021-2022': 39736.0},
 'CT': {'State_ID': 'CT',
  'State_name': 'Connecticut',
  'University': 'University of Connecticut',
  'In_State_Tuition_2007-2008': 8842,
  'In_State_Tuition_2008-2009': 9338,
  'In_State_Tuition_2009-2010': 9886,
  'In_State_Tuition_2010-2011': 10416,
  'In_State_Tuition_2011-2012': 10670,
  'In_State_Tuition_2012-2013': 11242,
  'In_State_Tuition_2013-2014': 12022,
  'In_State_Tuition_2014-2015': 12700,
  'In_State_Tuition_2015-2016': 13364,
  'In_State_Tuition_2016-2017': 14066,
  'In_State_Tuition_2017-2018': 14880,
  'In_State_Tuition_2018-2019': 15730.0,
  'In_State_Tuition_2019-2020': 17226,
  'In_State_Tuition_2020-2021': 17515.0,
  'In_State_Tuition_2021-2022': 17296.0,
  'Out_of_State_Tuition_2007-2008': 22786,
  'Out_of_State_Tuition_2008-2009': 24050,
  'Out_of_State_Tuition_2009-2010': 25584,
  'Out_of_State_Tuition_2010-2011': 26880,
  'Out_of_State_Tuition_2011-2012': 27566,
  'Out_of_State_Tuition_2012-2013': 29074,
  'Out_of_State_Tuition_2013-2014': 30970,
  'Out_of_State_Tuition_2014-2015': 32880,
  'Out_of_State_Tuition_2015-2016': 34908,
  'Out_of_State_Tuition_2016-2017': 35858,
  'Out_of_State_Tuition_2017-2018': 36948,
  'Out_of_State_Tuition_2018-2019': 38098,
  'Out_of_State_Tuition_2019-2020': 39894,
  'Out_of_State_Tuition_2020-2021': 42177.0,
  'Out_of_State_Tuition_2021-2022': 42200.0},
 'DE': {'State_ID': 'DE',
  'State_name': 'Delaware',
  'University': 'University of Delaware',
  'In_State_Tuition_2007-2008': 8150,
  'In_State_Tuition_2008-2009': 8646,
  'In_State_Tuition_2009-2010': 9486,
  'In_State_Tuition_2010-2011': 10208,
  'In_State_Tuition_2011-2012': 11192,
  'In_State_Tuition_2012-2013': 11682,
  'In_State_Tuition_2013-2014': 12112,
  'In_State_Tuition_2014-2015': 12342,
  'In_State_Tuition_2015-2016': 12520,
  'In_State_Tuition_2016-2017': 12830,
  'In_State_Tuition_2017-2018': 13160,
  'In_State_Tuition_2018-2019': 13680.0,
  'In_State_Tuition_2019-2020': 14280,
  'In_State_Tuition_2020-2021': 14729.0,
  'In_State_Tuition_2021-2022': 15501.0,
  'Out_of_State_Tuition_2007-2008': 19400,
  'Out_of_State_Tuition_2008-2009': 21126,
  'Out_of_State_Tuition_2009-2010': 23408,
  'Out_of_State_Tuition_2010-2011': 25408,
  'Out_of_State_Tuition_2011-2012': 27462,
  'Out_of_State_Tuition_2012-2013': 28772,
  'Out_of_State_Tuition_2013-2014': 29932,
  'Out_of_State_Tuition_2014-2015': 30692,
  'Out_of_State_Tuition_2015-2016': 31420,
  'Out_of_State_Tuition_2016-2017': 32250,
  'Out_of_State_Tuition_2017-2018': 33150,
  'Out_of_State_Tuition_2018-2019': 34310,
  'Out_of_State_Tuition_2019-2020': 35710,
  'Out_of_State_Tuition_2020-2021': 37083.0,
  'Out_of_State_Tuition_2021-2022': 38763.0},
 'FL': {'State_ID': 'FL',
  'State_name': 'Florida',
  'University': 'University of Florida',
  'In_State_Tuition_2007-2008': 3370,
  'In_State_Tuition_2008-2009': 3790,
  'In_State_Tuition_2009-2010': 4373,
  'In_State_Tuition_2010-2011': 5045,
  'In_State_Tuition_2011-2012': 5657,
  'In_State_Tuition_2012-2013': 6143,
  'In_State_Tuition_2013-2014': 6263,
  'In_State_Tuition_2014-2015': 6313,
  'In_State_Tuition_2015-2016': 6381,
  'In_State_Tuition_2016-2017': 6381,
  'In_State_Tuition_2017-2018': 6381,
  'In_State_Tuition_2018-2019': 6381.0,
  'In_State_Tuition_2019-2020': 6381,
  'In_State_Tuition_2020-2021': 6927.0,
  'In_State_Tuition_2021-2022': 7748.0,
  'Out_of_State_Tuition_2007-2008': 17791,
  'Out_of_State_Tuition_2008-2009': 20640,
  'Out_of_State_Tuition_2009-2010': 23744,
  'Out_of_State_Tuition_2010-2011': 27322,
  'Out_of_State_Tuition_2011-2012': 27934,
  'Out_of_State_Tuition_2012-2013': 28420,
  'Out_of_State_Tuition_2013-2014': 28540,
  'Out_of_State_Tuition_2014-2015': 28590,
  'Out_of_State_Tuition_2015-2016': 28658,
  'Out_of_State_Tuition_2016-2017': 28658,
  'Out_of_State_Tuition_2017-2018': 28658,
  'Out_of_State_Tuition_2018-2019': 28658,
  'Out_of_State_Tuition_2019-2020': 28658,
  'Out_of_State_Tuition_2020-2021': 29529.0,
  'Out_of_State_Tuition_2021-2022': 31297.0},
 'GA': {'State_ID': 'GA',
  'State_name': 'Georgia',
  'University': 'University of Georgia',
  'In_State_Tuition_2007-2008': 5259,
  'In_State_Tuition_2008-2009': 5532,
  'In_State_Tuition_2009-2010': 6172,
  'In_State_Tuition_2010-2011': 7338,
  'In_State_Tuition_2011-2012': 9472,
  'In_State_Tuition_2012-2013': 9842,
  'In_State_Tuition_2013-2014': 10262,
  'In_State_Tuition_2014-2015': 10836,
  'In_State_Tuition_2015-2016': 11622,
  'In_State_Tuition_2016-2017': 11634,
  'In_State_Tuition_2017-2018': 11818,
  'In_State_Tuition_2018-2019': 11830.0,
  'In_State_Tuition_2019-2020': 12080,
  'In_State_Tuition_2020-2021': 13530.0,
  'In_State_Tuition_2021-2022': 15004.0,
  'Out_of_State_Tuition_2007-2008': 20726,
  'Out_of_State_Tuition_2008-2009': 22343,
  'Out_of_State_Tuition_2009-2010': 25946,
  'Out_of_State_Tuition_2010-2011': 26946,
  'Out_of_State_Tuition_2011-2012': 27682,
  'Out_of_State_Tuition_2012-2013': 28052,
  'Out_of_State_Tuition_2013-2014': 28472,
  'Out_of_State_Tuition_2014-2015': 29046,
  'Out_of_State_Tuition_2015-2016': 29832,
  'Out_of_State_Tuition_2016-2017': 29844,
  'Out_of_State_Tuition_2017-2018': 30392,
  'Out_of_State_Tuition_2018-2019': 30404,
  'Out_of_State_Tuition_2019-2020': 31120,
  'Out_of_State_Tuition_2020-2021': 31934.0,
  'Out_of_State_Tuition_2021-2022': 32376.0},
 'HI': {'State_ID': 'HI',
  'State_name': 'Hawaii',
  'University': 'University of Hawaii at Manoa',
  'In_State_Tuition_2007-2008': 5390,
  'In_State_Tuition_2008-2009': 6259,
  'In_State_Tuition_2009-2010': 7168,
  'In_State_Tuition_2010-2011': 8096,
  'In_State_Tuition_2011-2012': 9100,
  'In_State_Tuition_2012-2013': 9404,
  'In_State_Tuition_2013-2014': 9904,
  'In_State_Tuition_2014-2015': 10620,
  'In_State_Tuition_2015-2016': 11164,
  'In_State_Tuition_2016-2017': 11732,
  'In_State_Tuition_2017-2018': 11732,
  'In_State_Tuition_2018-2019': 11970.0,
  'In_State_Tuition_2019-2020': 12186,
  'In_State_Tuition_2020-2021': 13323.0,
  'In_State_Tuition_2021-2022': 13969.0,
  'Out_of_State_Tuition_2007-2008': 14654,
  'Out_of_State_Tuition_2008-2009': 16915,
  'Out_of_State_Tuition_2009-2010': 19328,
  'Out_of_State_Tuition_2010-2011': 21536,
  'Out_of_State_Tuition_2011-2012': 23932,
  'Out_of_State_Tuition_2012-2013': 25652,
  'Out_of_State_Tuition_2013-2014': 27472,
  'Out_of_State_Tuition_2014-2015': 29412,
  'Out_of_State_Tuition_2015-2016': 31516,
  'Out_of_State_Tuition_2016-2017': 33764,
  'Out_of_State_Tuition_2017-2018': 33764,
  'Out_of_State_Tuition_2018-2019': 34002,
  'Out_of_State_Tuition_2019-2020': 34218,
  'Out_of_State_Tuition_2020-2021': 38265.0,
  'Out_of_State_Tuition_2021-2022': 40046.0},
 'IA': {'State_ID': 'IA',
  'State_name': 'Iowa',
  'University': 'University of Iowa',
  'In_State_Tuition_2007-2008': 6293,
  'In_State_Tuition_2008-2009': 6544,
  'In_State_Tuition_2009-2010': 6824,
  'In_State_Tuition_2010-2011': 7417,
  'In_State_Tuition_2011-2012': 7765,
  'In_State_Tuition_2012-2013': 8057,
  'In_State_Tuition_2013-2014': 8061,
  'In_State_Tuition_2014-2015': 8079,
  'In_State_Tuition_2015-2016': 8104,
  'In_State_Tuition_2016-2017': 8325,
  'In_State_Tuition_2017-2018': 8964,
  'In_State_Tuition_2018-2019': 9267.0,
  'In_State_Tuition_2019-2020': 9606,
  'In_State_Tuition_2020-2021': 9470.0,
  'In_State_Tuition_2021-2022': 9790.0,
  'Out_of_State_Tuition_2007-2008': 19465,
  'Out_of_State_Tuition_2008-2009': 20658,
  'Out_of_State_Tuition_2009-2010': 22445,
  'Out_of_State_Tuition_2010-2011': 23713,
  'Out_of_State_Tuition_2011-2012': 25099,
  'Out_of_State_Tuition_2012-2013': 26279,
  'Out_of_State_Tuition_2013-2014': 26931,
  'Out_of_State_Tuition_2014-2015': 27409,
  'Out_of_State_Tuition_2015-2016': 27890,
  'Out_of_State_Tuition_2016-2017': 28413,
  'Out_of_State_Tuition_2017-2018': 30608,
  'Out_of_State_Tuition_2018-2019': 31233,
  'Out_of_State_Tuition_2019-2020': 31569,
  'Out_of_State_Tuition_2020-2021': 32250.0,
  'Out_of_State_Tuition_2021-2022': 33384.0},
 'ID': {'State_ID': 'ID',
  'State_name': 'Idaho',
  'University': 'University of Idaho',
  'In_State_Tuition_2007-2008': 4410,
  'In_State_Tuition_2008-2009': 4632,
  'In_State_Tuition_2009-2010': 4932,
  'In_State_Tuition_2010-2011': 5402,
  'In_State_Tuition_2011-2012': 5856,
  'In_State_Tuition_2012-2013': 6212,
  'In_State_Tuition_2013-2014': 6524,
  'In_State_Tuition_2014-2015': 6784,
  'In_State_Tuition_2015-2016': 7020,
  'In_State_Tuition_2016-2017': 7232,
  'In_State_Tuition_2017-2018': 7488,
  'In_State_Tuition_2018-2019': 7864.0,
  'In_State_Tuition_2019-2020': 8304,
  'In_State_Tuition_2020-2021': 8639.0,
  'In_State_Tuition_2021-2022': 8965.0,
  'Out_of_State_Tuition_2007-2008': 14490,
  'Out_of_State_Tuition_2008-2009': 14712,
  'Out_of_State_Tuition_2009-2010': 15111,
  'Out_of_State_Tuition_2010-2011': 16994,
  'Out_of_State_Tuition_2011-2012': 18376,
  'Out_of_State_Tuition_2012-2013': 19000,
  'Out_of_State_Tuition_2013-2014': 19600,
  'Out_of_State_Tuition_2014-2015': 20314,
  'Out_of_State_Tuition_2015-2016': 21024,
  'Out_of_State_Tuition_2016-2017': 22040,
  'Out_of_State_Tuition_2017-2018': 23812,
  'Out_of_State_Tuition_2018-2019': 25500,
  'Out_of_State_Tuition_2019-2020': 27540,
  'Out_of_State_Tuition_2020-2021': 27428.0,
  'Out_of_State_Tuition_2021-2022': 27929.0},
 'IL': {'State_ID': 'IL',
  'State_name': 'Illinois',
  'University': 'University of Illinois at Urbana-Champaign',
  'In_State_Tuition_2007-2008': 11130,
  'In_State_Tuition_2008-2009': 12240,
  'In_State_Tuition_2009-2010': 12528,
  'In_State_Tuition_2010-2011': 13096,
  'In_State_Tuition_2011-2012': 13838,
  'In_State_Tuition_2012-2013': 14522,
  'In_State_Tuition_2013-2014': 14750,
  'In_State_Tuition_2014-2015': 15020,
  'In_State_Tuition_2015-2016': 15626,
  'In_State_Tuition_2016-2017': 15698,
  'In_State_Tuition_2017-2018': 15868,
  'In_State_Tuition_2018-2019': 16004.0,
  'In_State_Tuition_2019-2020': 16210,
  'In_State_Tuition_2020-2021': 17042.0,
  'In_State_Tuition_2021-2022': 17713.0,
  'Out_of_State_Tuition_2007-2008': 25216,
  'Out_of_State_Tuition_2008-2009': 26024,
  'Out_of_State_Tuition_2009-2010': 26336,
  'Out_of_State_Tuition_2010-2011': 27238,
  'Out_of_State_Tuition_2011-2012': 27980,
  'Out_of_State_Tuition_2012-2013': 28664,
  'Out_of_State_Tuition_2013-2014': 29132,
  'Out_of_State_Tuition_2014-2015': 29646,
  'Out_of_State_Tuition_2015-2016': 30786,
  'Out_of_State_Tuition_2016-2017': 31320,
  'Out_of_State_Tuition_2017-2018': 31988,
  'Out_of_State_Tuition_2018-2019': 32574,
  'Out_of_State_Tuition_2019-2020': 33352,
  'Out_of_State_Tuition_2020-2021': 34137.0,
  'Out_of_State_Tuition_2021-2022': 34431.0},
 'IN': {'State_ID': 'IN',
  'State_name': 'Indiana',
  'University': 'Indiana University Bloomington',
  'In_State_Tuition_2007-2008': 7837,
  'In_State_Tuition_2008-2009': 8231,
  'In_State_Tuition_2009-2010': 8613,
  'In_State_Tuition_2010-2011': 9028,
  'In_State_Tuition_2011-2012': 9524,
  'In_State_Tuition_2012-2013': 10033,
  'In_State_Tuition_2013-2014': 10209,
  'In_State_Tuition_2014-2015': 10388,
  'In_State_Tuition_2015-2016': 10388,
  'In_State_Tuition_2016-2017': 10388,
  'In_State_Tuition_2017-2018': 10533,
  'In_State_Tuition_2018-2019': 10681.0,
  'In_State_Tuition_2019-2020': 10947,
  'In_State_Tuition_2020-2021': 11335.0,
  'In_State_Tuition_2021-2022': 11928.0,
  'Out_of_State_Tuition_2007-2008': 22316,
  'Out_of_State_Tuition_2008-2009': 24769,
  'Out_of_State_Tuition_2009-2010': 26173,
  'Out_of_State_Tuition_2010-2011': 27689,
  'Out_of_State_Tuition_2011-2012': 29540,
  'Out_of_State_Tuition_2012-2013': 31483,
  'Out_of_State_Tuition_2013-2014': 32350,
  'Out_of_State_Tuition_2014-2015': 33241,
  'Out_of_State_Tuition_2015-2016': 33741,
  'Out_of_State_Tuition_2016-2017': 34246,
  'Out_of_State_Tuition_2017-2018': 34845,
  'Out_of_State_Tuition_2018-2019': 35456,
  'Out_of_State_Tuition_2019-2020': 36512,
  'Out_of_State_Tuition_2020-2021': 38297.0,
  'Out_of_State_Tuition_2021-2022': 40239.0},